include::variables.adoc[]

= Add-ons
:icons:
:toc: macro
:toc-title:
:toclevels: 1

toc::[]

[[add-ons-overview]]
== Overview

{project} allows you to extend the vanilla OpenShift setup provided by *cluster up* with an add-on mechanism.

Add-ons are directories that contain a text file with the *_.addon_* extension.
The directory can also contain other resource files such as JSON template files.
However, only one *_.addon_* file is allowed per add-on.

The following example shows the contents of an add-on file, including the name and description of the add-on, additional metadata, and the actual add-on commands to apply.

[[example-anyuid-addon]]
.Example: anyuid add-on definition file

----
# Name: anyuid                                                                          // <1>
# Description: Allows authenticated users to run images under a non pre-allocated UID   // <2>
# Required-Vars: ACME_TOKEN                                                             // <3>
# OpenShift-Version: >3.6.0                                                             // <4>

oc adm policy add-scc-to-group anyuid system:authenticated                              // <5>
----
<1> (Required) Name of the add-on.
<2> (Required) Description of the add-on.
<3> (Optional) Comma separated list of required interpolation variables. See xref:../using/addons.adoc#addon-variable-interpolation[Variable Interpolation]
<4> (Optional) OpenShift version required to run a specific add-on. See xref:../using/addons.adoc#addon-openshift-version-semantics[OpenShift Version Semantic]
<5> Actual add-on command. In this case, the command executes the *oc* binary.

[NOTE]
====
Comment lines, starting with the '#' character, can be inserted anywhere in the file.
====

Enabled add-ons are applied during xref:../command-ref/minishift_start.adoc#[`minishift start`], immediately after the initial cluster provisioning is successfully completed.

[[addon-openshift-version-semantics]]
== OpenShift-Version Semantics

As part of the add-on metadata you can specify the OpenShift version which needs to be running in order to apply the add-on.
To do so, you can specify the optional *OpenShift-Version* metadata field.
The semantics are as follows:

[cols="1,3"]
|===
| >3.6.0             | OpenShift version higher than 3.6.0 needs to be running in order to apply the add-on.
| >=3.6.0            | OpenShift version 3.6.0 or higher needs to be running in order to apply the add-on.
| 3.6.0              | OpenShift version 3.6.0 needs to be running in order to apply the add-on.
| >=3.5.0, <3.8.0    | OpenShift version should higher or equal to 3.5.0 but lower than 3.8.0.
| >=3.5.0, +<=3.8.0+ | OpenShift version should higher or equal to 3.5.0 but lower or equal to 3.8.0.
|===

[NOTE]
====
If the metadata field *OpenShift-Version* is not specified in the add-on header, the add-on can be applied against any version of OpenShift.
====

[NOTE]
====
*OpenShift-Version* only supports versions in the form of <major>.<minor>.<patch>.
====

[[addon-commands]]
== Add-on Commands

This section describes the commands that an add-on file can contain.
They form a small domain-specific language for {project} add-ons:

ssh::
If the add-on command starts with `ssh`, you can run any command within the {project}-managed VM.
This is similar to running xref:../command-ref/minishift_ssh.adoc#[`minishift ssh`] and then executing any command on the VM.
For more information about `minishift ssh` command usage, see xref:../using/basic-usage.adoc#connecting-with-ssh[Connecting to the {project} VM with SSH].

oc::
If the add-on command starts with `oc`, it uses the `oc` binary that is cached on your host to execute the specified `oc` command.
This is similar to running `oc --as system:admin ...` from the command line.
+
[NOTE]
====
The `oc` command is executed as *system:admin*.
====

openshift::
If the add-on command starts with `openshift`, you can run the *openshift* binary within the container that runs OpenShift.
This means that any file parameters or other system-specific parameters must match the environment of the container instead of your host.

docker::
If the add-on command starts with `docker`, it executes a `docker` command against the Docker daemon within the {project} VM.
This is the same daemon on which the single-node OpenShift cluster is running as well.
This is similar to running `eval $(minishift docker-env)` on your host and then executing any `docker` command.
See also xref:../command-ref/minishift_docker-env.adoc#[`minishift docker-env`].

echo::
If the add-on command starts with `echo`, the arguments following the `echo` command are printed to the console.
This can be used to provide additional feedback during add-on execution.

sleep::
If the add-on command starts with `sleep`, it waits for the specified number of seconds.
This can be useful in cases where you know that a command such as `oc` might take a few seconds before a certain resource can be queried.

[NOTE]
====
Trying to use an undefined command will cause an error when the add-on gets parsed.
====

[[addon-variable-interpolation]]
== Variable Interpolation

{project} allows the use of variables within the add-on commands.
Variables have the format `#{<variable-name>}`.
The following example shows how the OpenShift routing suffix can be interpolated into an `openshift` command to create a new certificate as part of securing the OpenShift registry.
The used variable `#{routing-suffix}` is part of the built-in add-on variables.

[[example-addon-routing-variable]]
.Example: Usage of the routing-suffix variable

----
$ openshift admin ca create-server-cert \
  --signer-cert=/var/lib/origin/openshift.local.config/master/ca.crt \
  --signer-key=/var/lib/origin/openshift.local.config/master/ca.key \
  --signer-serial=/var/lib/origin/openshift.local.config/master/ca.serial.txt \
  --hostnames='docker-registry-default.#{routing-suffix},docker-registry.default.svc.cluster.local,172.30.1.1' \
  --cert=/etc/secrets/registry.crt \
  --key=/etc/secrets/registry.key
----

[[addon-built-in-variables]]
=== Built-in Variables

There exist several built-in variables which are available for interpolation at all times.
The following table shows these variables.

[[table-supported-addon-variables]]
.Supported built-in add-on variables

|===
|Variable |Description

|ip
|IP of the {project} VM.

|routing-suffix
|OpenShift routing suffix for the application.

|addon-name
|Name of the current add-on.
|===

[[addon-dynamic-variables]]
=== Dynamic Variables

The commands xref:../command-ref/minishift_start.adoc#[`minishift start`] as well as xref:../command-ref/minishift_addons_apply.adoc#[`minishift addons apply`] also provide an `--addon-env` flag which allows to dynamically pass variables for interpolation, for example:

----
$ minishift addons apply --addon-env PROJECT_USER=john acme
----

The `--addon-env` flag can be specified multiple times to define more than one variables for interpolation.

Specifying dynamic variables also works in conjunction with xref:../using/basic-usage.adoc#setting-persistent-configuration-values[setting persistent configuration values].

----
$ minishift config set addon-env PROJECT_USER=john
$ minishift addons apply acme
----

[TIP]
====
Multiple variables need to be comma separated when the xref:../command-ref/minishift_config_set.adoc#[`minishift config set`] command is used.
====

There is also the possibility to dynamically interpolate a variable with the value of an environment variable at the time the add-on gets applied.
For this the variable value needs to be prefixed with _env_.

----
$ minishift config set addon-env PROJECT_USER=env.USER        // <1>
$ minishift addons apply acme                                 // <2>
----
<1> Using the _env_ prefix ensures that instead of literally replacing '#{PROJECT_USER}' with 'env.USER', the value of the environment variable `USER` is used.
If the environment variable is not set, interpolation does not occur.
<2> When the add-on is applied, each occurrence of `#{PROJECT_USER}` within an add-on command gets replaced with the value of the environment variable `USER`.

As an add-on developer, you can enforce that a variable value is provided when the add-on gets applied by adding the variable name to the _Required-Vars_ metadata header.
Multiple variables need to be comma separated.

----
# Name: acme
# Description: ACME add-on
# Required-Vars: PROJECT_USER
----

You can also provide default values for variables using the _Var-Defaults_ metadata header.
_Var-Defaults_ needs to be specified in the format of `<key>=<value>`.
Multiple default key/value pairs need to be comma separated.

----
# Name: acme
# Description: ACME add-on
# Required-Vars: PROJECT_USER
# Var-Defaults: PROJECT_USER=john
----

[NOTE]
====
`=` and `,` are metacharacters and cannot be used as part of keys or values.
====

[NOTE]
====
Variable values specified via the command line using the `--addon-env` or set via `minishift config set addon-env` have precedence over _Var-Defaults_.
====

[[default-addons]]
== Default Add-ons

{project} provides a set of built-in add-ons that offer some common OpenShift customization to assist with development.
To install the default add-ons, run:

----
$ minishift addons install --defaults
----

This command extracts the default add-ons to the add-on installation directory *_$MINISHIFT_HOME/addons_*.
To view the list of installed add-ons, you can then run:

----
$ minishift addons list --verbose=true
----

This command prints a list of installed add-ons.
You should at least see the *anyuid* add-on listed.
This is an important add-on that allows you to run images that do not use a pre-allocated UID.
By default, this is not allowed in OpenShift.

[[table-list-of-default-addons]]
.Default add-ons

[cols="1,3"]
|===
|Add-on Name    | Description

| anyuid
| Changes the default security context constraints to allow pods to run with arbitrary UID.

| admin-user
| Creates a user named 'admin' and assigns the *cluster-admin* role to it.  
| registry-route
| Creates an edge terminated route for the OpenShift registry.

| xpaas
| Imports xPaaS templates.
|===

[[addons-by-community]]
=== Add-ons by the Community

Apart from the several default add-ons, there are a number of community developed add-ons for {project}.
Community add-ons can be found in the link:https://github.com/minishift/minishift-addons/tree/master/add-ons[minishift-addons] repository.
You can get all the information about these add-ons in the link:https://github.com/minishift/minishift-addons[repository].
The instructions for installing them can be found in the link:https://github.com/minishift/minishift-addons/blob/master/README.adoc[README].

[[installing-addons]]
== Installing Add-ons

Add-ons are installed with the xref:../command-ref/minishift_addons_install.adoc#[`minishift addons install`] command.

The following example shows how to install an add-on.

[[example-install-addon]]
.Example: Installing an add-on

----
$ minishift addons install <path_to_addon_directory>
----

[[enabling-disabling-addons]]
== Enabling and Disabling Add-ons

Add-ons are enabled with the xref:../command-ref/minishift_addons_enable.adoc#[`minishift addons enable`] command and disabled with the xref:../command-ref/minishift_addons_disable.adoc#[`minishift addons disable`] command.
Enabled add-ons automatically get executed during xref:../command-ref/minishift_start.adoc#[`minishift start`].

The following examples show how to enable and disable the *anyuid* add-on.

[[example-enable-anyuid]]
.Example: Enabling the anyuid add-on

----
$ minishift addons enable anyuid
----

[[example-disable-anyuid]]
.Example: Disabling the anyuid add-on

----
$ minishift addons disable anyuid
----

[[addon-priorities]]
=== Add-on Priorities

When you enable an add-on, you can also specify a priority, which determines the order that the add-ons are applied.

The following example shows how to enable the *registry* add-on with a higher priority value.

[[example-enable-registry-priority]]
.Example: Enabling the registry add-on with priority

----
$ minishift addons enable registry --priority=5
----

The add-on priority attribute determines the order in which add-ons are applied.
By default, an add-on has the priority 0.
Add-ons with a lower priority value are applied first.

In the following example, the *anyuid*, *registry*, and *eap* add-ons are enabled with the respective priorities of 0, 5 and 10.
This means that *anyuid* is applied first, followed by *registry*, and lastly the *eap* add-on.

[[example-priority-list]]
.Example: List command output with explicit priorities

----
$ minishift addons list
- anyuid         : enabled    P(0)
- registry       : enabled    P(5)
- eap            : enabled    P(10)
----

[NOTE]
====
If two add-ons have the same priority the order in which they are getting applied is not determined.
====

[[apply-addons]]
== Applying Add-ons

Add-ons can be explicitly executed with the xref:../command-ref/minishift_addons_apply.adoc#[`minishift addons apply`] command.
You can use the `apply` command for both enabled and disabled add-ons.
To apply multiple add-ons with a single command, specify add-on names separated by space.

The following example shows how to explicitly apply the *anyuid* and the *admin-user* add-ons.

[[example-apply-anyuid-admin-user]]
.Example: Applying anyuid and admin-user add-ons

----
$ minishift addons apply anyuid admin-user
----

[[remove-addons]]
== Removing Add-ons

Add-ons can be removed with the xref:../command-ref/minishift_addons_remove.adoc#[`minishift addons remove`] command.
It is the mirror command to xref:../using/addons.adoc#apply-addons[`minishift addons apply`] and similarly can be used regardless whether the add-on is enabled or not.
Provided the specified add-on is installed and has a `<addon_name>.addon.remove` file, `minishift addons remove` will execute the commands specified in this file.

To remove multiple add-ons with a single command, specify the add-on names separated by space.
The following example shows how to explicitly remove the *admin-user* add-on.

[[example-remove-admin-user]]
.Example: Removing admin-user add-on

----
$ minishift addons remove admin-user
-- Removing addon 'admin-user':.
admin user deleted
----

[[uninstall-addons]]
== Uninstalling Add-ons

Add-ons can be uninstalled with the xref:../command-ref/minishift_addons_uninstall.adoc#[`minishift addons uninstall`] command.
It is the mirror command to xref:../command-ref/minishift_addons_install.adoc#[`minishift addons install`] and can be used regardless whether the add-on is enabled or not.
Provided the specified add-on is installed, `minishift addons uninstall` will delete the corresponding add-on directory from *_$MINISHIFT_HOME/addons_*.

The following example shows how to explicitly uninstall the *admin-user* add-on:

[[example-uninstall-admin-user]]
.Example: Uninstalling admin-user add-on

----
$ minishift addons uninstall admin-user
Add-on 'admin-user' uninstalled
----

[[custom-addons]]
== Writing Custom Add-ons

To write a custom add-on, you should create a directory and in it create at least one text file with the extension *_.addon_*, for example *_admin-role.addon_*.

This file needs to contain the *Name* and *Description* metadata fields, as well as the commands that you want to execute as a part of the add-on.

The following example shows the definition of an add-on that gives the developer user cluster-admin privileges.

[[example-admin-role]]
.Example: Add-on definition for admin-role

----
# Name: admin-role
# Description: Gives the developer user cluster-admin privileges

oc adm policy add-role-to-user cluster-admin developer
----

After you define the add-on, you can install it by running:

----
$ minishift addons install <ADDON_DIR_PATH>
----

[TIP]
====
You can also write metadata with multiple lines.

[[example-multiline-metadata]]
.Example: Add-on definition which contain multiline description
----
# Name: prometheus
# Description: This template creates a Prometheus instance preconfigured to gather OpenShift and
# Kubernetes platform and node metrics and report them to admins. It is protected by an
# OAuth proxy that only allows access for users who have view access to the prometheus
# namespace. You may customize where the images (built from openshift/prometheus
# and openshift/oauth-proxy) are pulled from via template parameters.
# Url: https://prometheus.io/
----
====

[NOTE]
====
You can also edit your add-on directly in the {project} add-on install directory *_$MINISHIFT_HOME/addons_*.
Be aware that if there is an error in the add-on, it will not show when you run any `addons` commands, and it will not be applied during the `minishift start` process.
====

To provide add-on remove instructions, you can create text file with the extension *_.addon.remove_*, for example *_admin-user.addon.remove_*.
Similar to the *_.addon_* file, it needs the *Name* and *Description* metadata fields.
If a *_.addon.remove_* file exists, it can be applied via the xref:../using/addons.adoc#remove-addons[`remove`] command.
