include::variables.adoc[]

= Experimental Features
:icons:
:toc: macro
:toc-title:
:toclevels: 2

toc::[]

[[experimental-features-overview]]
== Overview

If you want to get early access to some upcoming features and experiment, you can set the environment variable `MINISHIFT_ENABLE_EXPERIMENTAL`, which makes additional features flags available:

----
$ export MINISHIFT_ENABLE_EXPERIMENTAL=y
----

[IMPORTANT]
====
Experimental features are not officially supported, and might break or result in unexpected behavior.
To share your feedback on these features, you are welcome to link:https://github.com/minishift/minishift#community[contact the {project} community].
====

[[enabling-experimental-oc-flags]]
== Enabling Experimental `oc cluster up` Flags

By default, {project} does not expose all link:https://github.com/openshift/origin/blob/master/docs/cluster_up_down.md[`oc cluster up`] flags in the {project} CLI.

You can set the `MINISHIFT_ENABLE_EXPERIMENTAL` environment variable to enable the following options for the xref:../command-ref/minishift_start.adoc#[`minishift start`] command:

`service-catalog`::
Enables provisioning the OpenShift link:https://docs.openshift.org/latest/architecture/service_catalog/index.html[service catalog].

`extra-clusterup-flags`::
Enables passing flags that are not directly exposed in the {project} CLI directly to `oc cluster up`.

[[hyperv-static-ip]]
== Assign IP Address to Hyper-V

Since the Internal Virtual Switch for Hyper-V does not provide a DHCP offer option, an IP address needs to be provided in a different way.
For Hyper-V a functionality is provided to assign an IP address on startup using the Data Exchange Service.

[IMPORTANT]
====
This only works with the CentOS/RHEL based image in combination with Hyper-V.
The B2D image experiences a problem when the values are being sent to the {project} instance and consumed by the B2D iso.
We are looking into the issue and hope to provide a solution in the future.
====

To make this work you need to create a link:https://docs.microsoft.com/en-us/virtualization/hyper-v-on-windows/user-guide/setup-nat-network[Virtual Switch using NAT].

[NOTE]
====
WinNAT is limited to one NAT network per host.
For more details about capabilities, and limitations, please see the link:https://docs.microsoft.com/en-us/virtualization/hyper-v-on-windows/user-guide/setup-nat-network[WinNAT capabilities and limitations blog].
====

The following command will attempt to assign an IP address for use on the Internal Virtual Switch 'MyInternal':

----
PS> $env:MINISHIFT_ENABLE_EXPERIMENTAL="y"
PS> $env:HYPERV_VIRTUAL_SWITCH="MyInternal"
PS> minishift.exe start `
  --iso-url centos `
  --network-ipaddress 192.168.1.10 `
  --network-gateway 192.168.1.1 `
  --network-nameserver 8.8.8.8
----

If you want to use the 'DockerNAT' network, the following commands are needed to setup the correct NAT networking and assign an IP in the range expected:

----
PS> New-NetNat -Name SharedNAT -InternalIPInterfaceAddressPrefix 10.0.75.1/24
PS> $env:MINISHIFT_ENABLE_EXPERIMENTAL="y"
PS> $env:HYPERV_VIRTUAL_SWITCH="DockerNAT"
PS> minishift.exe start `
  --iso-url centos `
  --network-ipaddress 10.0.75.128 `
  --network-gateway 10.0.75.1 `
  --network-nameserver 8.8.8.8
----

[NOTE]
====
Be sure to specify a valid gateway and nameserver.
Failing to do so will result in connectivity issues.
====


[[set-fixed-ip]]
== Set Fixed IP Address

[NOTE]
====
Currently not supported on KVM as the driver plugin relies on the DHCP offer to determine the IP address.
====

Most hypervisors do not support extending the lease time when the IP is assigned using DHCP.
This might lead to a new IP getting assigned to the VM after a restart as it will conflict with the security certificates generated for the old IP.
This will make {project} completely unusable.

For this purpose, {project} includes the functionality to set a static address to the VM. This will prevent it from changing between restarts. However, it will not work on all the driver plugins at the moment due to the way the IP address is resolved.

The following command will set the IP address that was assigned as fixed:

----
$ minishift ip --set-static 
----

If you prefer to use dynamic assignment, you can use:

----
$ minishift ip --set-dhcp
----
