include::variables.adoc[]

= Experimental Features
:icons:
:toc: macro
:toc-title:
:toclevels: 2

toc::[]

[[experimental-features-overview]]
== Overview

If you want to get early access to some upcoming features and experiment, you can set the environment variable `MINISHIFT_ENABLE_EXPERIMENTAL`, which makes additional feature flags available:

----
$ export MINISHIFT_ENABLE_EXPERIMENTAL=y
----

[IMPORTANT]
====
Experimental features are not officially supported, and might break or result in unexpected behavior.
To share your feedback on these features, you are welcome to link:https://github.com/minishift/minishift#community[contact the {project} community].
====

[[enabling-experimental-oc-flags]]
== Enabling Experimental `oc cluster up` Flags

By default, {project} does not expose all link:https://github.com/openshift/origin/blob/master/docs/cluster_up_down.md[`oc cluster up`] flags in the {project} CLI.

You can set the `MINISHIFT_ENABLE_EXPERIMENTAL` environment variable to enable the following options for the xref:../command-ref/minishift_start.adoc#[`minishift start`] command:

`extra-clusterup-flags`::
Enables passing flags directly to `oc cluster up` that are not directly exposed in the {project} CLI.

For example, the following command will pass the `--service-catalog` flag to `oc cluster up` to provision the OpenShift link:https://docs.openshift.org/latest/architecture/service_catalog/index.html[*service catalog*]:

----
$ MINISHIFT_ENABLE_EXPERIMENTAL=y minishift start --extra-clusterup-flags "--service-catalog"
----

[[set-fixed-ip]]
== Set Fixed IP Address

[IMPORTANT]
====
This only works with the CentOS or RHEL xref:../using/basic-usage.adoc#choosing-iso-image[ISO] and is currently not supported on KVM as the driver plug-in relies on the DHCP offer to determine the IP address.
====

include::con_static-ip-overview.adoc[]

The following command will set the IP address that was assigned as fixed:

----
$ minishift ip --set-static 
----

If you prefer to use dynamic assignment, you can use:

----
$ minishift ip --set-dhcp
----


[[local-dns-server]]
== Local DNS Server

{project} provides a DNS server for offline usage or the possibility of overriding DNS records while testing.
This will allow you to access the OpenShift routes without Internet.

[NOTE]
====
The DNS server is specific to a profile.
====

Starting the DNS server can be done as follows:

----
$ minishift dns start
----

After starting the DNS server you need to configure your device settings to use this nameserver. The start command will show you a temporary option that can be used when you entered offline usage.

[NOTE]
====
In the current implementation you need to start the server and do required changes in the host settings manually.
The DNS configuration is not permanent and might reset when the network state of the device changes.
====

Stopping the DNS server can be done as follows:

----
$ minishift dns stop
----

To get the status of the DNS server:

----
$ minishift dns status
----
