include::variables.adoc[]

= Host Folders
:icons:
:toc: macro
:toc-title:
:toclevels: 2

toc::[]

[[host-folders-overview]]
== Overview

Host folders are directories on the host which are shared between the host and the {project} VM.
This allows for two way file synchronization between the host and the VM.
The following sections discuss usage of the `minishift hostfolder` command.

[[minishift-hostfolder-command]]
== The minishift hostfolder Command

{project} provides the xref:../command-ref/minishift_hostfolder.adoc#[`minishift hostfolder`] command to list, add, mount, unmount and remove host folders.
You can use the `hostfolder` command to mount multiple shared folders onto custom specified mount points.

[NOTE]
====
Currently link:https://en.wikipedia.org/wiki/Server_Message_Block[CIFS] and link:https://en.wikipedia.org/wiki/SSHFS[SSHFS] based host folders are supported.
SSHFS support is experimental.
====

[NOTE]
====
SSHFS based host folders are not working with the xref:../using/basic-usage#choosing-iso-image[minikube ISO] for now, because it is missing the sshfs dependency.
This will be addressed in a future release of the minikube ISO.
====

[[host-folder-prerequisite]]
=== Prerequisites

==== CIFS

To use the `minishift hostfolder` command for CIFS based host folders, you need to be able to share directories using CIFS.
On Windows, CIFS is the default technology for sharing directories.
For example, on Windows 10 the *_C:\Users_* directory is shared by default and can be accessed by locally-authenticated users.

It is also possible to use CIFS on macOS and Linux.
On macOS, you can enable CIFS-based shares under *System Preferences > Sharing*.
See link:https://support.apple.com/en-us/HT204445[How to connect with File Sharing on your Mac] for detailed setup instructions.

On Linux, follow your distribution-specific instructions to install link:https://www.samba.org[Samba].

==== SSHFS

SSHFS based host folders work without prerequisite.

[[displaying-host-folders]]
=== Displaying Host Folders

The xref:../command-ref/minishift_hostfolder_list.adoc#[`minishift hostfolder list`] command gives you an overview of the defined host folders, their names, mount points, remote paths and whether they are currently mounted.

An example output could look like:

----
$ minishift hostfolder list
Name    Type    Source               Mountpoint       Mounted
test    sshfs   /Users/john/test     /mnt/sda1/test   N
----

In this example, there is a sshfs based host folder with the name **test** which mounts *_/Users/john/test_* onto *_/mnt/sda1/test_* in the {project} VM.
The share is currently not mounted.

[[adding-host-folders]]
=== Adding Host Folders

The xref:../command-ref/minishift_hostfolder_add.adoc#[`minishift hostfolder add`] command allows you to define a new host folder.

The exact syntax to use depends on the host folder type.
Independent of the type you can choose between non-interactive and interactive configuration.
The default it non-interactive.
By specifying the `--interactive` you can select the interactive configuration mode.

The following sections give examples for configuring CIFS and SSHFS host folders.

==== CIFS

[[adding-cifs-hostfolder]]
.Adding a CIFS based hostfolder
----
$ minishift hostfolder add -t cifs --source //192.168.99.1/MYSHARE --target /mnt/sda1/myshare --options username=john,password=mysecret,domain=MYDOMAIN myshare
----

The above command will create a new host folder with the name of **myshare**.
The source of the host folder is the UNC path *_//192.168.99.1/MYSHARE_* which is required.
The target or mount point is *_/mnt/sda1/myshare_* within the {project} VM.
Using the `--options` flag host folder type specific options can be specified using a list of comma separated key/value pairs.
In the case of a CIFS host folder the required options are the user name for the CIFS share as well as the password.
Via the the `--options` flag the domain of the share can be specified as well.
Often this can be left out, but for example on Windows, when your account is linked to a Microsoft account, you must use the Microsoft account email address as user name as well as your machine name as displayed by `$env:COMPUTERNAME` as a domain.

[TIP]
====
On Windows hosts, the `minishift hostfolder add` command also provides a `users-share` option.
When this option is specified, no UNC path needs to be specified and *_C:\Users_* is assumed.
====

[WARNING]
====
When you use the Boot2Docker ISO with the VirtualBox driver, VirtualBox guest additions are automatically enabled and occupy the *_/Users_* mount point.
====

==== SSHFS

[[adding-cifs-hostfolder]]
.Adding a SSHFS based hostfolder
----
$ minishift hostfolder add -t sshfs --source /Users/john/myshare --target /mnt/sda1/myshare myshare
----

For the case of a SSHFS based host folder only the source and target of the host folder need to be specified.

[[instance-host-folders]]
==== Instance-Specific Host Folders

By default, host folder definitions are persistent, similar to other xref:../using/basic-usage.adoc#persistent-configuration[persistent configuration] options.
This means that these host folder definitions will survive the deletion and subsequent re-creation of a {project} VM.

In some cases you might want to define a host folder just for a specific {project} instance.
To do so, you can use the `--instance-only` flag of the xref:../command-ref/minishift_hostfolder_add.adoc#[`minishift hostfolder add`] command.
Host folder definitions that are created with the `--instance-only` flag will be removed together with any other instance-specific state during xref:../command-ref/minishift_delete.adoc#[`minishift delete`].

[[mounting-host-folders]]
=== Mounting Host Folders

After you have added host folders, you use the xref:../command-ref/minishift_hostfolder_mount.adoc#[`minishift hostfolder mount`] command to mount a host folder by its name:

----
$ minishift hostfolder mount myshare
----

You can verify that the host folder is mounted by running:

----
$ minishift hostfolder list
Name       Mountpoint          Remote path              Mounted
myshare    /mnt/sda1/myshare   //192.168.99.1/MYSHARE   Y
----

Alternatively, you can list the actual content of the mounted host folder:

----
$ minishift ssh "ls -al /mnt/sda1/myshare"
----

[TIP]
====
When mounting SSHFS based host folders a SFTP server process is started on port 2022 of the host.
Make sure that your network and firewall settings allow this port to be opened.
If you need to configure this port you can make use of {project}'s xref:../using/basic-usage.adoc#persistent-configuration[persistent configuration] using the key `hostfolders-sftp-port`, for example:

----
$ minishift config set hostfolders-sftp-port 2222
----
====

[[auto-mounting-host-folders]]
==== Auto-Mounting Host Folders

Host folders can also be mounted automatically each time you run xref:../command-ref/minishift_start.adoc#[`minishift start`].
To set auto-mounting, you need to set the `hostfolders-automount` option in the {project} configuration file.

----
$ minishift config set hostfolders-automount true
----

After the `hostfolders-automount` option is set, {project} will attempt to mount all defined host folders during `minishift start`.

[[umounting-host-folders]]
=== Unmounting Host Folders

You use the xref:../command-ref/minishift_hostfolder_umount.adoc#[`minishift hostfolder umount`] command to unmount a host folder.

----
$ minishift hostfolder umount myshare

$ minishift hostfolder list
Name       Mountpoint          Remote path              Mounted
myshare    /mnt/sda1/myshare   //192.168.99.1/MYSHARE   N
----

[[deleting-host-folders]]
=== Deleting Host Folders

You use the xref:../command-ref/minishift_hostfolder_remove.adoc#[`minishift hostfolder remove`] command to remove a host folder definition.

----
$ minishift hostfolder list
Name        Mountpoint            Remote path              Mounted
myshare     /mnt/sda1/myshare     //192.168.1.82/MYSHARE   N

$ minishift hostfolder remove myshare

$ minishift hostfolder list
No host folders defined
----
