include::variables.adoc[]

= Image Caching
:icons:
:toc: macro
:toc-title:
:toclevels: 1

toc::[]

[[image-caching-overview]]
== Overview

To speed up provisioning of the OpenShift cluster and to minimize network traffic, the core OpenShift images can be cached on the host.
This feature is considered experimental and needs to be explicitly enabled.

[[image-chaching-configuration]]
== Image Caching Configuration

To enable image caching you use the xref:../command-ref/minishift_config_set#[`minishift config set`] command:

----
$ minishift config set image-caching true
----

Once enabled, caching occurs transparently, in a background process, the first time you use the xref:../command-ref/minishift_start#[`minishift start`] command.
Once the images are cached under *_$MINISHIFT_HOME/cache/images_*, successive {project} VM creations will use these cached images.

Each time an image exporting background process runs, a log file is generated under *_$MINISHIFT_HOME/logs_* which can be used to verify the progress of the export.

You can disable the caching of the OpenShift images by setting `image-caching` to `false` or removing the setting altogether using xref:../command-ref/minishift_config_unset#[`minishift config unset`]:

----
$ minishift config unset image-caching
----

[NOTE]
====
Image caching is considered experimental and its semantics and API are subject to change.
The aim is to allow caching of arbitrary images, as well as using a better format for storing the images on the host.
You can track the progress on this feature on GitHub issue link:https://github.com/minishift/minishift/issues/952[#952].
====
