include::variables.adoc[]

[[interacting-with-openshift]]
= Interacting with OpenShift
:icons:
:toc: macro
:toc-title:
:toclevels: 2

toc::[]

[[interacting-openshift-overview]]
== Overview

Minishift creates a virtual machine (VM) and provisions a local, single-node OpenShift
cluster in this VM. The following sections describe how Minishift can assist you in
interacting with and configuring your local OpenShift instance.

For details about managing the Minishift VM, see the link:../using/managing-minishift{outfilesuffix}[Managing Minishift] section.

[[openshift-client-binary]]
== Using the OpenShift client binary (oc)

The `minishift start` command creates an OpenShift instance using the
https://github.com/openshift/origin/blob/master/docs/cluster_up_down.md[cluster up] approach.

For this purpose it copies the `oc` binary onto your host. It is located in the  _~/.minishift/cache/oc/{openshift-version}_ directory, provided you use Minishift's default version of OpenShift.
You can add this binary to your `PATH` using link:../command-ref/minishift_oc-env{outfilesuffix}[`minishift oc-env`] which displays the command you need to type into your shell.
The output of `oc-env` differs depending on the operating system and the shell type.

----
$ minishift oc-env
export PATH="/Users/john/.minishift/cache/oc/v1.5.0:$PATH"
# Run this command to configure your shell:
# eval $(minishift oc-env)
----

As part of the `minishift start` command there is also a `minishift`
https://docs.openshift.org/latest/cli_reference/manage_cli_profiles.html[oc context] created.
This context contains the configuration to communicate with your OpenShift cluster.

Minishift activates this context automatically, but if you need to switch back to it after
for example, logging into another OpenShift instance, you can run:

----
$ oc config use-context minishift
----

For an introduction to `oc` usage, see the
https://docs.openshift.com/enterprise/3.2/cli_reference/get_started_cli.html[Get Started with the CLI]
topic in the OpenShift documentation.

[[log-into-cluster]]
=== Logging into the cluster

By default, _cluster up_ uses
https://docs.openshift.org/latest/install_config/configuring_authentication.html#AllowAllPasswordIdentityProvider[AllowAllPasswordIdentityProvider]
to authenticate against the local cluster. This means any non-empty user name and password can
be used to login to the local cluster. The recommended user name and password combination is
developer/developer, because it already has a default project _myproject_ and also can
https://docs.openshift.org/latest/architecture/additional_concepts/authentication.html#authentication-impersonation[impersonate]
the administrator. This allows you to run administrator commands using the `--as system:admin` parameter.

To login as administrator, use the system account:

----
$ oc login -u system:admin
----

In this case, https://docs.openshift.com/enterprise/3.2/architecture/additional_concepts/authentication.html#api-authentication[client certificates]
are used. The certificates are stored in `~/.kube/config`. The _cluster up_ command
installs the appropriate certificates as a part of the bootstrap.

[NOTE]
====
If you run the command `oc login -u system -p admin`, you will log in but not as an administrator.
Instead, you will be logged in as an unprivileged user with no particular rights.
====

To view the currently available login contexts, run:

----
$ oc config view
----

[[access-web-console]]
=== Accessing the Web console

To access the https://docs.openshift.org/latest/architecture/infrastructure_components/web_console.html[OpenShift console],
you can run this command in a shell after starting Minishift to get the URL of the Web console:

----
$ minishift console --url
----

Alternatively, after starting Minishift, you can use the following command
to directly open the console in a browser:

----
$ minishift console
----

[[access-openshift-services]]
=== Accessing OpenShift services

To access a service exposed with a node port, run this command in a
shell after starting Minishift to get the address:

----
$ minishift openshift service [-n NAMESPACE] [--url] NAME
----

[[view-openshift-logs]]
=== Viewing OpenShift logs

To access OpenShift logs, run the `logs` command after starting Minishift:

----
$ minishift logs
----

[[update-openshift-config]]
== Updating OpenShift configuration

While OpenShift is running, you can view and change the master or the
node configuration of your cluster.

To view the current OpenShift master configuration
(_master-config.yaml_), run the following command:

----
$ minishift openshift config view
----

To show the node configuration instead of the master configuration,
specify the `target` flag.

For details about the `view` command, see the link:../command-ref/minishift_openshift_config_view{outfilesuffix}[synopsis]
command reference.

NOTE: After you update the OpenShift configuration, OpenShift will transparently restart.

[[example-config-cors]]
=== Example: Configuring cross-origin resource sharing

In this example, you configure https://en.wikipedia.org/wiki/Cross-origin_resource_sharing[cross-origin resource sharing] (CORS)
by updating the OpenShift master configuration to allow additional IP addresses to request resources.

By default, OpenShift only allows cross-origin resource requests from the IP address of the
cluster or from localhost. This setting is stored in the `corsAllowedOrigins` property of the
https://docs.openshift.com/enterprise/3.0/admin_guide/master_node_configuration.html#master-configuration-files[master configuration]
file (_master-config.yaml_).

To change the property value and allow cross-origin requests from all domains, run the following command:

----
$  minishift openshift config set --patch '{"corsAllowedOrigins": [".*"]}'
----

[NOTE]
====
If you get the error `The specified patch need to be a valid JSON.` when you run the above command,
you need to modify the above command depending on your Operating System,
your shell environment and its interpolation behavior.

For example, if you use PowerShell on Windows 7 or 10 modify the above command to:

....
$ minishift openshift config set --patch '{\"corsAllowedOrigins\": [\".*\"]}'
....

If you use Command Prompt you may need to use:

....
$ minishift openshift config set --patch "{\"corsAllowedOrigins\": [\".*\"]}"
....

====

[[example-change-openshift-routing-suffix]]
=== Example: Changing the OpenShift routing suffix

In this example, you change the OpenShift routing suffix in the master configuration.

If you use a static routing suffix, you can set the `routing-suffix` flag as part of the
link:../command-ref/minishift_start{outfilesuffix}[`start`] command. By default, Minishift uses a
dynamic routing prefix based on http://nip.io/[nip.io], in which the IP address of the VM is a
part of the routing suffix, for example _192.168.99.103.nip.io_.

If you experience issues with `nip.io`, you can use http://xip.io/[xip.io], which is
based on the same principles.

To set the routing suffix to `xip.io`, run the following command:

----
$ minishift openshift config set --patch '{"routingConfig": {"subdomain": "<IP-ADDRESS>.xip.io"}}'
----

Make sure to replace `IP-ADDRESS` in the above example with the IP address of your Minishift VM.
You can retrieve the IP address by running the link:../command-ref/minishift_ip{outfilesuffix}[`ip`] command.
