// Need to add 'minishift' prefix to keep Asciibinder happy. This fails on local build
// https://github.com/redhataccess/ascii_binder/issues/60
include::minishift/variables.adoc[]

[[interacting-with-openshift]]
= Interacting with OpenShift
:icons:
:toc: macro
:toc-title:
:toclevels: 1

toc::[]

Minishift creates a virtual machine (VM) and provisions a local,
single-node OpenShift cluster in this VM. The following sections
describe how Minishift can assist you with interacting with and
configuring your local OpenShift instance.

For details about managing the Minishift VM, see the link:../using/managing-minishift{outfilesuffix}[Managing Minishift] section.

[[openshift-client-binary]]
== OpenShift client binary (oc)

The `minishift start` command creates an OpenShift instance using the
https://github.com/openshift/origin/blob/master/docs/cluster_up_down.md[cluster up] approach.

For this purpose it copies the `oc` binary onto your host. Provided you
are using the default version of OpenShift, you find it under
`~/.minishift/cache/oc/{openshift-version}/oc`. You can add this
binary to your `PATH` variable in order to use `oc`, for example:

[subs="verbatim,attributes"]
----
$ export PATH=$PATH:~/.minishift/cache/oc/{openshift-version}
----

In future versions we will provide a command to assist in setting up the
`PATH`.
See GitHub issue https://github.com/minishift/minishift/issues/142[#142].

As part of the `minishift start` command there is also a `minishift`
https://docs.openshift.org/latest/cli_reference/manage_cli_profiles.html[oc context] created.
This context contains the configuration to communicate with your OpenShift cluster.

Minishift activates this context automatcally, but if you need to switch back to it after,
for example logging into another OpenShift instance, you can run:

----
$ oc config use-context minishift
----

For an introduction to `oc` usage, refer to the
https://docs.openshift.com/enterprise/3.2/cli_reference/get_started_cli.html[Get Started with the CLI]
topic in the OpenShift documentation.

[[log-into-cluster]]
=== Logging into the cluster

By default, _cluster up_ uses
https://docs.openshift.org/latest/install_config/configuring_authentication.html#AllowAllPasswordIdentityProvider[AllowAllPasswordIdentityProvider]
to authoenticate against the local cluster. This means any non-empty user name and password can
be used to login to the local cluster. The recommended user name and password combination is
developer/developer, because it already has a default project _myproject_ and also can
https://docs.openshift.org/latest/architecture/additional_concepts/authentication.html#authentication-impersonation[impersonate]
the administrator user. This allows to run admin commands using the `--as system:admin` parameter.

To login as administrator, use the system account:

----
$ oc login -u system:admin
----

In this case, https://docs.openshift.com/enterprise/3.2/architecture/additional_concepts/authentication.html#api-authentication[client certificates]
are used. The certificates are stored in `~/.kube/config`. The _cluster up_ command
installs the appropriate certificates as a part of the bootstrap.

[NOTE]
====
If you run the command `oc login -u system -p admin`, you will log in but not as an administrator.
Instead, you will be logged in as an unprivileged user with no particular rights.
====

To view the currently available login contexts, run:

----
$ oc config view
----

[[access-web-console]]
=== Accessing the Web console

To access the https://docs.openshift.org/latest/architecture/infrastructure_components/web_console.html[OpenShift console],
you can run this command in a shell after starting Minishift to get the URL of the Web console:

----
$ minishift console --url
----

Alternatively, after starting Minishift, you can use the following command
to directly open the console in a browser:

----
$ minishift console
----

[[access-openshift-services]]
=== Accessing OpenShift services

To access a service exposed with a node port, run this command in a
shell after starting Minishift to get the address:

----
$ minishift openshift service [-n NAMESPACE] [--url] NAME
----

[[view-openshift-logs]]
=== Viewing OpenShift logs

To access OpenShift logs, run the `logs` command after starting Minishift:

----
$ minishift logs
----

[[update-openshift-config]]
== Updating OpenShift configuration

While OpenShift is running, you can view and change the master or the
node configuration of your cluster.

To view the current OpenShift master configuration
(_master-config.yaml_), run the following command:

----
$ minishift openshift config view
----

To show the node configuration instead of the master configuration,
specify the `target` flag.

For details about the `view` command, see the link:../command-ref/minishift_openshift_config_view{outfilesuffix}[synopsis]
command reference.

NOTE: After you update the OpenShift configuration, OpenShift will transparently restart.

[[example-config-cors]]
=== Example: Configuring cross-origin resource sharing

In this example, you configure https://en.wikipedia.org/wiki/Cross-origin_resource_sharing[cross-origin resource sharing] (CORS)
by updating the OpenShift master configuration to allow additional IP addresses to request resources.

By default, OpenShift only allows cross-origin resource requests from the IP address of the
cluster or from localhost. This setting is stored in the `corsAllowedOrigins` property of the
https://docs.openshift.com/enterprise/3.0/admin_guide/master_node_configuration.html#master-configuration-files[master configuration]
file (_master-config.yaml_).

To change the property value and allow cross-origin requests from all domains, run the following command:

----
$  minishift openshift config set --patch '{"corsAllowedOrigins": [".*"]}'
----

[[example-change-openshift-routing-suffix]]
=== Example: Changing the OpenShift routing suffix

In this example, you change the OpenShift routing suffix in the master configuration.

If you use a static routing suffix, you can set the `routing-suffix` flag as part of the
link:../command-ref/minishift_start{outfilesuffix}[`start`] command. By default, Minishift uses a
dynamic routing prefix based on http://nip.io/[nip.io], in which the IP address of the VM is a
part of the routing suffix, for example _192.168.99.103.nip.io_.

If you experience issues with `nip.io`, you can use http://xip.io/[xip.io], which is
based on the same principles.

To set the routing suffix to `xip.io`, run the following command:

----
$ minishift openshift config set --patch '{"routingConfig": {"subdomain": "<IP-ADDRESS>.xip.io"}}'
----

Make sure to replace `IP-ADDRESS` in the above example with the IP address of your Minishift VM.
You can retrieve the IP address by running the link:../command-ref/minishift_ip{outfilesuffix}[`ip`] command.

[[persistent-volumes]]
== Persistent volumes

Minishift supports https://docs.openshift.org/latest/dev_guide/persistent_volumes.html[PersistentVolumes]
of type `hostPath`. These persisten volumes are mapped to a directory inside the Minishift VM.

The MiniShift VM boots into a tmpfs, so most directories will not be persisted across
reboots, for example if you use `minishift stop`. However, MiniShift is configured to
persist OpenShift-specific configuration files and some Docker files.

The files that are persisted are stored in the following host directories:

- `/var/lib/minishift`
- `/var/lib/docker`

The following example shows persistent volume configuration to persist data
in the `/var/lib/minishift` directory:

----
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 5Gi
  hostPath:
    path: /var/lib/minishift/pv
----

User-configured persistent volumes are currently under development.
See GitHub issue https://github.com/minishift/minishift/issues/389[#389].
