[[managing-minishift]]
= Managing Minishift
:icons:
:toc: macro
:toc-title:
:toclevels: 1

toc::[]

[[managing-minishift-intro]]
== Managing Minishift

When you use Minishift, you interact with two components:

- a virtual machine (VM) created by Minishift
- the OpenShift cluster provisioned by Minishift within the VM

The following sections contain information about managing the Minishift VM.
For details about using Minishift to manage your local OpenShift cluster,
see the link:../using/interacting-with-openshift{outfilesuffix}[Interacting with OpenShift] section.

[[minishift-start-intro]]
=== Minishift start

The link:../command-ref/minishift_start{outfilesuffix}[`minishift start`] command creates and
configures the Minishift VM and provisions a local, single-node
OpenShift instance within the VM.

The command also copies the `oc` binary to your host so that you can interact
with OpenShift through the `oc` command line tool or through the Web console,
which can be accessed through the URL provided in the output
of the `minishift start` command.

[[minishift-stop-intro]]
=== Minishift stop

The link:../command-ref/minishift_stop{outfilesuffix}[`minishift stop`] command stops your OpenShift cluster and
shuts down the Minishift VM, but preserves the OpenShift cluster state.

Starting Minishift again will restore the OpenShift cluster, allowing
you to continue working from the last session. However, you must enter the same
parameters that you used in the original start command.

Efforts to further refine this experience are in progress. For details, see
the GitHub issue https://github.com/minishift/minishift/issues/179[#179].

[[minishift-delete-intro]]
=== Minishift delete

The link:../command-ref/minishift_delete{outfilesuffix}[`minishift delete`] command deletes the OpenShift cluster,
and also shuts down and deletes the Minishift VM. No data or state are preserved.

[[runtime-options]]
== Runtime options

The runtime behavior of Minishift can be controlled through flags,
environment variables, and persistent configuration options.

The following precedence order is applied to control the behavior of
Minishift. Each action in the following list takes precedence over
the action below it:

.  Use command-line flags as specified in the link:#flags[Flags] section.
.  Set environment variables as described in the
link:#environment-variables[Environment variables] section.
.  Use persistent configuration options as described in the
link:#persistent-configuration[Persistent configuration] section.
.  Accept the default value as defined by Minishift.

[[flags]]
=== Flags

You can use command line flags with Minishift to specify options and
direct its behavior. This has the highest precedence. Almost all
commands have flags, although different commands might have different flags.
Some of the commonly used command line flags of the `minishift start`
command are `cpus`, `memory` or `vm-driver`.

[[environment-variables]]
=== Environment variables

Minishift allows you to specify command-line flags you commonly use
through environment variables.
To do so, apply the following rules to the flag you want to set as an
environment variable.

.  Apply `MINISHIFT_` as a prefix to the flag you want to set as an
environment variable. For example, the `vm-driver` flag
 of the link:../command-ref/minishift_start{outfilesuffix}[`minishift start`] command becomes
`MINISHIFT_vm-driver`.
.  Use uppercase characters for the flag, so `MINISHIFT_vm-driver` in the above
example becomes `MINISHIFT_VM-DRIVER`.
.  Replace `-` with `_`, so `MINISHIFT_VM-DRIVER` becomes `MINISHIFT_VM_DRIVER`.

Environment variables can be used to replace any option of any Minishift
command. A common example is the URL of the ISO to be used. Usually, you
specify it with the `iso-url` flag of the `minishift start` command.
Applying the above rules, you can also specify this URL by setting the environment
variable as `MINISHIFT_ISO_URL`.

NOTE: You can also use the `MINISHIFT_HOME` environment variable, to
choose a different home directory for Minishift. By default, Minishift
places all runtime state into `~/.minishift`. This environment variable is
currently experimental and semantics might change in future releases.

[[persistent-configuration]]
=== Persistent configuration

Using persistent configuration allows you to control the Minishift
behavior without specifying actual command line flags, similar to the
way you use link:#environment-variables[environment variables].

Minishift maintains a configuration file in
`$MINISHIFT_HOME/config/config.json`. This file can be
used to set commonly-used command-line flags persistently.

NOTE: Persistent configuration can only be applied to the set of
supported configuration options that are listed in the synopsis of the
link:./minishift_config.html[`minishift config`] sub-command, unlike
environment variables that can be used to replace any option of any
command.

[[setting-persistent-configuration-values]]
==== Setting persistent configuration values

The easiest way to change a persistent configuration option is with
the link:../command-ref/minishift_config_set{outfilesuffix}[`config set`] sub-command. For example:

[source,sh]
----
# Set default memory 4096 MB
$ minishift config set memory 4096
----

To view all persistent configuration values, you can use the
link:../command-ref/minishift_config_view{outfilesuffix}[`view`] sub-command:

[source,sh]
----
$ minishift config view
- memory: 4096
----

Alternatively, you can display a single value with the
link:../command-ref/minishift_config_get{outfilesuffix}[`get`] sub-command:

[source,sh]
----
$ minishift config get memory
4096
----

[[unsetting-persistent-configuration-values]]
==== Unsetting persistent configuration values

To remove a persistent configuration option, you can use the
link:../command-ref/minishift_config_unset{outfilesuffix}[`unset`] sub-command. For example:

[source,sh]
----
$ minishift config unset memory
----

[[addons]]
== Addons

Minishift allows to configure the vanilla OpenShift setup as provided by _cluster up_ via a so called
addon mechanism.

Addons are directories, containing at least one text file with the _addon_ extension. There can be other
resource files, for example JSON template files, in the directory as well, but only one _addon_ file
is allowed.

An example addon can be seen in <<example-anyuid-addon>>.

[[example-anyuid-addon]]
.Example of anyuid addon defintion
----
# Name: anyuid // <1>
# Description: Allows authenticated users to run images under a non pre-allocated UID // <2>
# Url: https://access.redhat.com/documentation/en-us/openshift_enterprise/3.2/html/cluster_administration/admin-guide-manage-scc <3>

oc adm policy add-scc-to-group anyuid system:authenticated <4>
----
<1> Defines the mandatory name of the addon.
<2> Provides the mandatory description of the addon.
<3> Additional meta data and comments which are ignored by Minishift
<4> Actual addon command. In this case an execution of the _oc_ binary. See <<section-addon-commands>>
for a full list of supported addon commands.

As we can see in <<example-anyuid-addon>> each addon contains some meta information
as well as a list of commands which will be executed.

NOTE: Comment lines can be inserted at anywhere in the file and need to start with the '#' character.

Enabled addons (see <<section-enabling-disabling-addons>>) will then be applied during
link:../command-ref/minishift_start{outfilesuffix}[`minishift start`], right after the initial
cluster up provisioning has successfully completed.

[[section-addon-commands]]
=== Addon commands

Now that we have seen how an addon looks like, let's look at the command types an addon file can
contain and what one can do with them. At the moment there are five command types which form a sort
of mini DSL for addons.

ssh::
An addon command which start with _ssh_, allows you to run any command within the Minishift managed VM.
This is comparable to running link:../command-ref/minishift_ssh{outfilesuffix}[`minishift ssh`] and
then executing any sort of command on the VM.
oc::
An addon command which start with _oc_, uses the _oc_ binary cached on your host to execute the
specified `oc` command. This equivalent to running `oc --as system:admin ...` from the command line.
+
NOTE: The oc command is executed as _system:admin_
openshift::
An addon command which start with _openshift_, allows you to run the `openshift` binary within
the container running OpenShift. This means any file parameters or other system specific parameters
need be matching the environment of the container, not your host.
docker::
An addon command which start with _docker_, executes a `docker` command against the Docker daemon
within the Minishift VM. This is the same daemon on which the OpenShift single node cluster is
running as well. This is comparable to running `eval $(minishift docker-env)` on your host and
then executing any `docker` command. See also
link:../command-ref/minishift_docker-env{outfilesuffix}[`minishift docker-env`].
sleep::
An addon command which start with _sleep_, waits for the specified number of seconds. This can be
useful where it is known that for example an `oc` command takes a few seconds before a certain
resource can be queried.

NOTE: Trying to add a command not listed above will create an error when the addon gets parsed.

=== Built-in addons

Minishift provides a set of built-in addons which offer some common OpenShift customization
useful for development. To install these built-in addons run:

[[example-install-default-addons]]
[source,sh]
----
$ minishift addons install --defaults
----

This command will extract the built-in addons into the addon installation directory
(`$MINISHIFT_HOME/addons`). To view the list of installed addons, you can then run:

[[example-list-addons]]
[source,sh]
----
$ minishift addons list --verbose=true
----

This will print a list of installed addons. You should at least see the _anyuid_ addon listed.
This is an important addon which allows you to run images which do not use a pre-allocated UID.
This is per default not allowed in OpensShift.

<<section-enabling-disabling-addons>> will show you how you can for example enable or disable
the _anyuid_ addon.

[[section-enabling-disabling-addons]]
=== Enabling and disabling addons

Addons are enabled and disabled with the
link:../command-ref/minishift_addons_enable{outfilesuffix}[`minishift addons enable`] resp. the
link:../command-ref/minishift_addons_disable{outfilesuffix}[`minishift addons disable`] command.
<<example-enable-anyuid>> and <<example-disable-anyuid>> show how this looks like for the
_anyuid_ addon.

[[example-enable-anyuid]]
.Enabling the anyuid addon
[source,sh]
----
$ minishift addons enable anyuid
----

[[example-disable-anyuid]]
.Disabling the anyuid addon
[source,sh]
----
$ minishift addons disable anyuid
----

==== Addon priorities

As part of the enabling an addon, one can also specify a priority as seen in
<<example-enable-registry-priority>>.

[[example-enable-registry-priority]]
.Enabling the registry addon with priority
[source,sh]
----
$ minishift addons enable --priority=5
----

Priority determines the order in which addons are getting applied. Per default a addon has
the priority 0. Addons with a lower priority get applied first. For example:

[[example-priority-list]]
.Example of list command with explicit priorities
[source,sh]
----
$ minishift addons list
- anyuid         : enabled    P(0)
- registry       : enabled    P(5)
- eap            : enabled    P(10)
----

In <<example-priority-list>> three addons are enabled - anyuid, registry and eap with the respective
priorities of 0, 5 and 10. This means anyuid gets applied first, followed by registry and lastly
the eap addon gets applied.

NOTE: If two addons have the same priority the order in which they are getting applied is not
determined.

=== Writing custom addons

To write a custom addon you should create a directory and within it create at least one
text file with the extension _.addon_, for example `admin-role.addon`.

This file needs to contain the _Name_ and _Description_ metadata as well as the commands
you want to be executed as part of the addon. <<example-admin-role>> shows how this could
look like.

[[example-admin-role]]
.Giving developer user cluster-admin privileges
----
# Name: admin-role
# Description: Gives the developer user cluster-admin privileges

oc adm policy add-role-to-user cluster-admin developer
----

Once you have your addon defined, you can install it via:

[[example-install-custom-addon]]
.Installing a custom addon
[source,sh]
----
$ minishift addons install <path to addon directory>
----

NOTE: You can also edit your addon directly in the Minishift addon install directory
`$MINISHIFT_HOME/addons`. Be aware that if there is an error in the addon it won't appear
in any of the _addons_ commands nor will it be applied during the `minishift start` process.

[[http-s-proxies]]
== HTTP/HTTPS Proxies

If you are behind a HTTP/HTTPS proxy, you need to supply proxy options
to allow Docker and OpenShift to work properly. To do this, pass the required
flags during `minishift start`.

For example:

[source,sh]
----
$ minishift start --http-proxy http://YOURPROXY:PORT --https-proxy https://YOURPROXY:PORT
----

In an authenticated proxy environment, the `proxy_user` and
`proxy_password` must be a part of proxy URI.

[source,sh]
----
 $ minishift start --http-proxy http://<proxy_username>:<proxy_password>@YOURPROXY:PORT \
                   --https-proxy https://<proxy_username>:<proxy_password>YOURPROXY:PORT
----

You can also use the `--no-proxy` flag to specify a comma-separated list of hosts
that should not be proxied. For a list of all available options, see the
link:../command-ref/minishift_start{outfilesuffix}[synopsis] of the `start` command.

Using the proxy options will transparently configure the Docker daemon
and OpenShift to use the specified proxies.

NOTE: Using the proxy options requires that you run OpenShift version 1.5.0-alpha.2 or later.
Use the `openshift-version` option to request a specific version of OpenShift. You can list
all Minishift-compatible OpenShift versions with
the link:../command-ref/minishift_openshift_list-versions{outfilesuffix}[`minishift openshift list-versions`] command.

[[mounted-host-folders]]
== Mounted host folders

Some drivers mount a host folder within the VM so that you can share files between the VM and the host.
These folders are not currently configurable, and are different for each driver and OS that you use.

[cols=",,,",options="header",]
|========================================
|Driver |OS |HostFolder |VM
|Virtualbox |Linux |/home |/hosthome
|Virtualbox |OSX |/Users |/Users
|Virtualbox |Windows |C://Users |/c/Users
|VMWare Fusion |OSX |/Users |/Users
|Xhyve |OSX |/Users |/Users
|========================================

NOTE: Host folder sharing is not implemented in the KVM and Hyper-V driver. You can
link:#mounting-custom-shared-folders[mount a CIFS-based shared folder] inside the VM instead.

[[mounting-custom-shared-folders]]
=== Mounting custom shared folders

The Minishift https://github.com/minishift/minishift-b2d-iso[Boot2Docker] ISO and the
Minishift https://github.com/minishift/minishift-centos-iso[CentOS] ISO include `cifs-utils`
and `fuse-sshfs`. These tools allows you to mount host folders using
https://en.wikipedia.org/wiki/Server_Message_Block[CIFS]
or https://en.wikipedia.org/wiki/SSHFS[SSHFS].

NOTE: When you use the Boot2Docker ISO along with the VirtualBox driver, VirtualBox
guest additions are automatically enabled and occupy the _/Users_ mountpoint as
shown in the following examples. In this case you need to use a different mountpoint.

[[cifs-folder-mount]]
==== Mounting folders with CIFS

In this example, you use CIFS-based sharing to mount `C:\Users` on a Windows host
into the Minishift VM. On Windows 10, the `C:\Users` folder is shared by default
and only needs locally-authenticated users.

.  Find the local IP address from the same network segment as your
Minishift instance.
+
----
$ Get-NetIPAddress | Format-Table`
----

.  Create a mountpoint and mount the shared folder.
+
[source,sh]
----
$ minishift ssh "sudo mkdir -p /Users"
$ minishift ssh "sudo mount -t cifs //[machine-ip]/Users /Users -o username=[username],password=[password],domain=$env:computername
----
+
If no error appears, the mount succeeded.

.  Verify the share mount.
+
[source,sh]
----
$ minishift ssh "ls -al /Users"
----
A successful mount will show a folder with the authenticated user name.

[NOTE]
====
- If you use this method to mount the folder, you might encounter issues
if your password string contains a `$` sign, because this is used by PowerShell
as a variable to be replaced. You can use `'` (single quotes) instead and
replace the value of `$env:computername` with the contents of this variable.

- If your Windows account is linked to a Microsoft account, you must use
the full Microsoft account email address to authenticate, your Microsoft account password,
and the domain name of your machine that contains your computername parameter.
====

[[sshfs-folder-mount]]
==== Mounting folders with SSHFS

You can use SSHFS-based host folder mounts when you have an SSH daemon
running on your host. Normally, this prerequisite is met by default on Linux and Mac OS X.

Most Linux distributions have an SSH daemon installed. If not, follow the instructions
for your specific distribution to install an SSH daemon. Mac OS X also has a built-in
SSH server. To use it, make sure that _Remote Login_ is enabled in _System Preferences > Sharing_.

On Windows, it is recommended to use link:#cifs-folder-mount[CIFS-based mount], but if
you want to try SSHFS you can install https://winscp.net/eng/docs/guide_windows_openssh_server[OpenSSH for Windows].

The following procedure shows an example of how to mount folders with SSHFS.

. Run `ifconfig` (or `Get-NetIPAddress` on Windows) to determine the local IP
address from the same network segment as your Minishift instance.

.  Create a mountpoint and mount the shared folder.
+
[source,sh]
----
$ minishift ssh "sudo mkdir -p /Users/<username>"
$ minishift ssh "sudo chown -R docker /Users"
$ minishift ssh
$ sshfs <username>@<IP>:/Users/<username>/ /Users
----

. Verify the share mount.
+
[source,sh]
----
$ minishift ssh "ls -al /Users/<username>"
----

[[networking]]
== Networking

The Minishift VM is exposed to the host system with a host-only IP address that
can be obtained with the `minishift ip` command.
