include::variables.adoc[]

= Managing {project}
:icons:
:toc: macro
:toc-title:
:toclevels: 2

toc::[]

[[managing-minishift-overview]]
== Overview

When you use {project}, you interact with two components:

- a virtual machine (VM) created by {project}
- the OpenShift cluster provisioned by {project} within the VM

The following sections contain information about managing the {project} VM.
For details about using {project} to manage your local OpenShift cluster, see the xref:../openshift/index.adoc#[Interacting with OpenShift] section.

[[minishift-life-cycle]]
== {project} Life-cycle

[[minishift-start-overview]]
=== {project} start Command

The xref:../command-ref/minishift_start.adoc#[`minishift start`] command creates and configures the {project} VM and provisions a local, single-node OpenShift cluster within the {project} VM.

The command also copies the *oc* binary to your host so that you can interact with OpenShift through the `oc` command-line tool or through the Web console, which can be accessed through the URL provided in the output of the `minishift start` command.

[[minishift-stop-overview]]
=== {project} stop Command

The xref:../command-ref/minishift_stop.adoc#[`minishift stop`] command stops your OpenShift cluster and shuts down the {project} VM, but preserves the OpenShift cluster state.

Starting {project} again will restore the OpenShift cluster, allowing you to continue working from the last session.
However, you must enter the same parameters that you used in the original start command.

Efforts to further refine this experience are in progress.
For details, see the GitHub issue link:https://github.com/minishift/minishift/issues/179[#179].

[[minishift-delete-overview]]
=== {project} delete Command

The xref:../command-ref/minishift_delete.adoc#[`minishift delete`] command deletes the OpenShift cluster, and also shuts down and deletes the {project} VM.
No data or state are preserved.

[[choosing-iso-image]]
== Choosing the ISO Image

When you start {project}, it downloads a live ISO image that the hypervisor uses to provision the {project} VM.

The following ISO images are available:

- link:https://github.com/minishift/minishift-b2d-iso/releases[{project} Boot2Docker] (Default).
This ISO image is based on link:https://github.com/boot2docker/boot2docker[Boot2Docker], which is a lightweight Linux distribution customized to run Docker containers.
The image size is small and optimized for development but not for production.

- link:https://github.com/minishift/minishift-centos-iso/releases[{project} CentOS].
This ISO image is based on link:https://www.centos.org/[CentOS], which is an enterprise-ready Linux distribution that more closely resembles a production environment.
The image size is larger than the Boot2Docker ISO image.

- link:https://github.com/kubernetes/minikube/tree/master/deploy/iso/minikube-iso[minikube ISO].
This ISO image is provided by link:https://github.com/kubernetes/minikube/[Minikube project]. It is a customized Linux and based on link:https://www.kernel.org/[upstream kernel].
Minikube ISO image also provides alternate container runtime e.g. cri-o and rkt along with docker.
Please check link:https://github.com/kubernetes/minikube/blob/master/docs/contributors/minikube_iso.md[Minikube documentation] for details.

NOTE: Minikube ISO image use is experimental in {project}. Work is in progress to make it as stable as CentOS and Boot2Docker ISO images.

By default, {project} uses the {project} Boot2Docker ISO image.
To choose the {project} CentOS ISO image instead, you can do one of the following:

- Use the *centos* alias to download and use the latest CentOS ISO:
+
----
$ minishift start --iso-url centos
----

- Specify explicitly the download URL of the {project} CentOS ISO image. For example:
+
[subs="attributes"]
----
$ minishift start --iso-url https://github.com/minishift/minishift-centos-iso/releases/download/{centos-iso-version}/minishift-centos7.iso
----

- Manually download the {project} CentSO ISO image from the link:https://github.com/minishift/minishift-centos-iso/releases[releases page] and enter the file URI to the image:
+
----
$ minishift start --iso-url file:///<path_to_ISO_image>
----

NOTE: You cannot run {project} with both ISO images concurrently.
To switch between ISO images, delete the {project} instance and start a new instance with the ISO image that you want to use.

[[runtime-options]]
== Runtime Options

The runtime behavior of {project} can be controlled through flags, environment variables, and persistent configuration options.

The following precedence order is applied to control the behavior of {project}.
Each action in the following list takes precedence over the action below it:

.  Use command-line flags as specified in the xref:flags[Flags] section.
.  Set environment variables as described in the xref:environment-variables[Environment Variables] section.
.  Use persistent configuration options as described in the xref:persistent-configuration[Persistent Configuration] section.
.  Accept the default value as defined by {project}.

[[flags]]
=== Flags

You can use command line flags with {project} to specify options and direct its behavior.
This has the highest precedence.
Almost all commands have flags, although different commands might have different flags.
Some of the commonly-used command line flags of the `minishift start` command are `cpus`, `memory` or `vm-driver`.

[[environment-variables]]
=== Environment Variables

{project} allows you to specify command-line flags you commonly use through environment variables.
To do so, apply the following rules to the flag you want to set as an environment variable.

.  Apply `MINISHIFT_` as a prefix to the flag you want to set as an environment variable.
For example, the `vm-driver` flag of the xref:../command-ref/minishift_start.adoc#[`minishift start`] command becomes `MINISHIFT_vm-driver`.
.  Use uppercase characters for the flag, so `MINISHIFT_vm-driver` in the above example becomes `MINISHIFT_VM-DRIVER`.
.  Replace `-` with `_`, so `MINISHIFT_VM-DRIVER` becomes `MINISHIFT_VM_DRIVER`.

Environment variables can be used to replace any option of any {project} command.
A common example is the URL of the ISO to be used.
Usually, you specify it with the `iso-url` flag of the `minishift start` command.
Applying the above rules, you can also specify this URL by setting the environment variable as `MINISHIFT_ISO_URL`.

NOTE: You can also use the `MINISHIFT_HOME` environment variable, to choose a different home directory for {project}.
By default, {project} places all runtime state into *_~/.minishift_*.
This environment variable is currently experimental and semantics might change in future releases.

[[persistent-configuration]]
=== Persistent Configuration

Using persistent configuration allows you to control the {project} behavior without specifying actual command line flags, similar to the way you use environment variables.

{project} maintains a configuration file in *_$MINISHIFT_HOME/config/config.json_*.
This file can be used to set commonly-used command-line flags persistently.

NOTE: Persistent configuration can only be applied to the set of supported configuration options that are listed in the synopsis of the xref:../command-ref/minishift_config.adoc#[`minishift config`] sub-command.
This is different from environment variables, which can be used to replace any option of any command.

[[setting-persistent-configuration-values]]
==== Setting Persistent Configuration Values

The easiest way to change a persistent configuration option is with the xref:../command-ref/minishift_config_set.adoc#[`minishift config set`] sub-command.
For example:

----
# Set default memory 4096 MB
$ minishift config set memory 4096
----

Flags which can be used multiple times per command invocation, like `docker-env` or `insecure-registry`, need to be comma-separated when used with the `config set` command.
For example, from the CLI, you can use `insecure-registry` like this:

----
$ minishift start --insecure-registry hub.foo.com --insecure-registry hub.bar.com
----

If you want to configure the same registries in the persistent configuration, you would run:

----
$ minishift config set insecure-registry hub.foo.com,hub.bar.com
----

To view all persistent configuration values, you can use the xref:../command-ref/minishift_config_view.adoc#[`minishift config view`] sub-command:

----
$ minishift config view
- memory: 4096
----

Alternatively, you can display a single value with the xref:../command-ref/minishift_config_get.adoc#[`minishift config get`] sub-command:

----
$ minishift config get memory
4096
----

[[unsetting-persistent-configuration-values]]
==== Unsetting Persistent Configuration Values

To remove a persistent configuration option, you can use the xref:../command-ref/minishift_config_unset.adoc#[`minishift config unset`] sub-command.
For example:

----
$ minishift config unset memory
----

[[driver-specific-environment-variables]]
=== Driver-Specific Environment Variables

You can also set driver-specific environment variables.
Each docker-machine driver supports its own set of options and variables.
A good starting point is the official docker-machine link:https://docs.docker.com/machine/drivers/[driver documentation].

xhyve and KVM documentation is available under their respective GitHub repository link:https://github.com/zchee/docker-machine-driver-xhyve[docker-machine-driver-xhyve] and https://github.com/dhiltgen/docker-machine-kvm[docker-machine-kvm].

To use driver-specific options, make sure to export the variable as defined in its driver documentation before running xref:../command-ref/minishift_start.adoc#[`minishift start`].
For example, the xhyve experimental NFS sharing can be enabled by executing:

----
$ export XHYVE_EXPERIMENTAL_NFS_SHARE=true
$ minishift start --vm-driver xhyve
----

CAUTION: Driver-specific options might overlap with values specified using {project}-specific flags and environment variables.
Examples are boot2docker URL, memory size, cpu count, and so on.
In this case, driver-specific environment variables will override {project}-specific settings.

[[caching-openshift-images]]
== Caching OpenShift images (experimental)

To speed up provisioning of the OpenShift cluster and to minimize network traffic, the core OpenShift images can be cached on the host.
This feature is considered experimental and needs to be explicitly enabled using the xref:../command-ref/minishift_config_set#[`minishift config set`] command:

----
$ minishift config set image-caching true
----

Once enabled, caching occurs transparently, in a background process, the first time you use the xref:../command-ref/minishift_start#[`minishift start`] command.
Once the images are cached under _$MINISHIFT_HOME/cache/images_, successive {project} VM creations will use these cached images.

Each time an image exporting background process runs, a log file is generated under _$MINISHIFT_HOME/logs_ which can be used to verify the progress of the export.

You can disable the caching of the OpenShift images by setting `image-caching` to `false` or removing the setting altogether using xref:../command-ref/minishift_config_unset#[`minishift config unset`]:

----
$ minishift config unset image-caching
----

NOTE: Image caching is considered experimental and its semantics and API is subject to change.
The aim is to allow caching of arbitrary images, as well as using a better format for storing the images on the host.
You can track the progress on this feature on the GitHub issue link:https://github.com/minishift/minishift/issues/952[#952].

[[persistent-volumes]]
== Persistent Volumes

As part of the OpenShift cluster provisioning, 100 link:https://docs.openshift.org/latest/dev_guide/persistent_volumes.html[persistent volumes] are created for your OpenShift cluster.
This allows applications to make link:https://docs.openshift.org/latest/dev_guide/persistent_volumes.html#persistent-volumes-claims-as-volumes-in-pods[persistent volumes claims].
The location of the persistent data is determined in the `host-pv-dir` flag of the xref:../command-ref/minishift_start.adoc#[`minishift start`] command and defaults to *_/var/lib/minishift/openshift.local.pv_* on the {project} VM.

[[http-s-proxies]]
== HTTP/HTTPS Proxies

If you are behind an HTTP/HTTPS proxy, you need to supply proxy options to allow Docker and OpenShift to work properly.
To do this, pass the required flags during `minishift start`.

For example:

----
$ minishift start --http-proxy http://YOURPROXY:PORT --https-proxy https://YOURPROXY:PORT
----

In an authenticated proxy environment, the `proxy_user` and `proxy_password` must be a part of proxy URI.

----
 $ minishift start --http-proxy http://<proxy_username>:<proxy_password>@YOURPROXY:PORT \
                   --https-proxy https://<proxy_username>:<proxy_password>@YOURPROXY:PORT
----

You can also use the `--no-proxy` flag to specify a comma-separated list of hosts that should not be proxied.

Using the proxy options will transparently configure the Docker daemon as well as OpenShift to use the specified proxies.

[NOTE]
====
- `minishift start` honors the environment variables `HTTP_PROXY`, `HTTPS_PROXY` and `NO_PROXY`.
If these variables are set, they are implicitly used during `minishift start` unless explicitly overridden by the corresponding command line flags.

- Using the proxy options requires that you run OpenShift version 1.5.0 or later.
Use the `openshift-version` option to request a specific version of OpenShift.
You can list all {project}-compatible OpenShift versions with the xref:../command-ref/minishift_openshift_version_list.adoc#[`minishift openshift version list`] command.
====

[[networking]]
== Networking

The {project} VM is exposed to the host system with a host-only IP address that can be obtained with the xref:../command-ref/minishift_ip.adoc#[`minishift ip`] command.

[[connecting-with-ssh]]
== Connecting to the {project} VM with SSH

You can use the xref:../command-ref/minishift_ssh.adoc#[`minishift ssh`] command to interact with the {project} VM.

You can run `minishift ssh` without a sub-command to open an interactive shell and run commands on the {project} VM in the same way that you run commands interactively on any remote machine using SSH.

You can also run `minishift ssh` with a sub-command to send the sub-command directly to the {project} VM and return the result to your local shell.
For example:

----
$ minishift ssh -- docker ps
CONTAINER    IMAGE                   COMMAND                CREATED        STATUS        NAMES
71fe8ff16548 openshift/origin:v1.5.1 "/usr/bin/openshift s" 4 minutes ago  Up 4 minutes  origin
----

[[experimental-features]]
== Experimental Features

If you want to get early access to some upcoming features and experiment, you can enable some of those in {project}.

You do this by setting the environment variable `MINISHIFT_ENABLE_EXPERIMENTAL`, which makes additional flags available:

----
$ export MINISHIFT_ENABLE_EXPERIMENTAL=y
----

[IMPORTANT]
====
Experimental features are not officially supported, and might break or result in unexpected behavior.
To share your feedback on these features, you are welcome to link:https://github.com/minishift/minishift#community[contact the {project} community].
====

[[enabling-experimental-oc-flags]]
=== Enabling experimental `oc cluster up` flags in `minishift start`

By default, {project} does not expose all link:https://github.com/openshift/origin/blob/master/docs/cluster_up_down.md[`oc cluster up`] flags in the {project} CLI.

You can set the `MINISHIFT_ENABLE_EXPERIMENTAL` environment variable to enable the following options for the xref:../command-ref/minishift_start.adoc#[`minishift start`] command:

`service-catalog`::
Enables provisioning the OpenShift link:https://docs.openshift.org/latest/architecture/service_catalog/index.html[service catalog].

`extra-clusterup-flags`::
Enables passing flags that are not directly exposed in the {project} CLI directly to `oc cluster up`.


[[hyperv-static-ip]]
=== Assign IP address to Hyper-V (experimental)

Since the Internal Virtual Switch for Hyper-V does not provide a DHCP offer option, an IP address needs to be provided in a different way.
For Hyper-V a functionality is provided to assign an IP address on startup using the Data Exchange Service.

[IMPORTANT]
====
-  While the default image is B2D, this only works with the CentOS/RHEL based image in combination with Hyper-V. The B2D image experiences
   a problem when the values are being send to the {project} instance and consumed by the B2D iso. We are looking into the issue and hope
   to provide a solution in the coming future.
====

To make this work you need to create a Virtual Switch using NAT

- link:https://docs.microsoft.com/en-us/virtualization/hyper-v-on-windows/user-guide/setup-nat-network[Set up a NAT network]


[NOTE]
====
WinNAT is limited to one NAT network per host. For more details about capabilities, and limitations, please see the link:https://docs.microsoft.com/en-us/virtualization/hyper-v-on-windows/user-guide/setup-nat-network[WinNAT capabilities and limitations blog]
====

The following command will attempt to assign an IP address for use on the Internal Virtual Switch 'MyInternal'.

----
PS> $env:MINISHIFT_ENABLE_EXPERIMENTAL="y"
PS> $env:HYPERV_VIRTUAL_SWITCH="MyInternal"
PS> minishift.exe start `
  --iso-url centos `
  --network-ipaddress 192.168.1.10 `
  --network-gateway 192.168.1.1 `
  --network-nameserver 8.8.8.8
----


If you want to use the 'DockerNAT' network, the following commands are needed to setup the correct NAT networking and assigning an IP in the range expected.

----
PS> New-NetNat -Name SharedNAT -InternalIPInterfaceAddressPrefix 10.0.75.1/24
PS> $env:MINISHIFT_ENABLE_EXPERIMENTAL="y"
PS> $env:HYPERV_VIRTUAL_SWITCH="DockerNAT"
PS> minishift.exe start `
  --iso-url centos `
  --network-ipaddress 10.0.75.128 `
  --network-gateway 10.0.75.1 `
  --network-nameserver 8.8.8.8
----

[NOTE]
====
- Be sure to specify a valid gateway and nameserver. Failing to do so will result in connectivity issuesi
====

