[[mounting-host-folders]]
= Host Folders
:icons:
:toc: macro
:toc-title:
:toclevels: 1

toc::[]

[[mount-host-folders-overview]]
== Overview

Some drivers mount a host folder within the VM so that you can share files between the VM and the host.
These folders are not currently configurable, and are different for each driver and OS that you use.

[cols=",,,",options="header",]
|========================================
|Driver |OS |HostFolder |VM
|Virtualbox |Linux |/home |/hosthome
|Virtualbox |OSX |/Users |/Users
|Virtualbox |Windows |C://Users |/c/Users
|VMWare Fusion |OSX |/Users |/Users
|Xhyve |OSX |/Users |/Users
|========================================

NOTE: Host folder sharing is not implemented in the KVM and Hyper-V drivers. You can
link:#mounting-custom-shared-folders[mount a CIFS-based shared folder] inside the VM instead.

[[mounting-custom-shared-folders]]
== Mounting custom shared folders

The Minishift https://github.com/minishift/minishift-b2d-iso[Boot2Docker] ISO and the
Minishift https://github.com/minishift/minishift-centos-iso[CentOS] ISO include `cifs-utils`
and `fuse-sshfs`. These tools allow you to mount host folders using
https://en.wikipedia.org/wiki/Server_Message_Block[CIFS]
or https://en.wikipedia.org/wiki/SSHFS[SSHFS].

NOTE: When you use the Boot2Docker ISO along with the VirtualBox driver, VirtualBox
guest additions are automatically enabled and occupy the _/Users_ mountpoint as
shown in the following examples. In this case you need to use a different mountpoint.

[[cifs-folder-mount]]
=== Mounting folders with CIFS

In this example, you use CIFS-based sharing to mount `C:\Users` on a Windows host
into the Minishift VM. On Windows 10, the `C:\Users` folder is shared by default
and only needs locally-authenticated users.

.  Find the local IP address from the same network segment as your
Minishift instance.
+

----
$ Get-NetIPAddress | Format-Table
----

.  Create a mountpoint and mount the shared folder.
+

----
$ minishift ssh "sudo mkdir -p /Users"
$ minishift ssh "sudo mount -t cifs //[machine-ip]/Users /Users -o username=[username],password=[password],domain=$env:computername
----
+
If no error appears, the mount succeeded.

.  Verify the share mount.
+

----
$ minishift ssh "ls -al /Users"
----
A successful mount will show a folder with the authenticated user name.

[NOTE]
====
- If you use this method to mount the folder, you might encounter issues
if your password string contains a `$` sign, because this is used by PowerShell
as a variable to be replaced. You can use `'` (single quotes) instead and
replace the value of `$env:computername` with the contents of this variable.

- If your Windows account is linked to a Microsoft account, you must use
the full Microsoft account email address to authenticate your Microsoft account password,
and the domain name of your machine that contains your computername parameter.
====

[[sshfs-folder-mount]]
=== Mounting folders with SSHFS

You can use SSHFS-based host folder mounts when you have an SSH daemon
running on your host. Normally, this prerequisite is met by default on Linux and Mac OS X.

Most Linux distributions have an SSH daemon installed. If not, follow the instructions
for your specific distribution to install an SSH daemon.

Mac OS X also has a built-in
SSH server. To use it, make sure that _Remote Login_ is enabled in _System Preferences > Sharing_.

On Windows, it is recommended to use link:#cifs-folder-mount[CIFS-based mount], but if
you want to try SSHFS you can install https://winscp.net/eng/docs/guide_windows_openssh_server[OpenSSH for Windows].

The following procedure shows an example of how to mount folders with SSHFS.

. Run `ifconfig` (or `Get-NetIPAddress` on Windows) to determine the local IP
address from the same network segment as your Minishift instance.

.  Create a mountpoint and mount the shared folder.
+

----
$ minishift ssh "sudo mkdir -p /Users/<username>"
$ minishift ssh "sudo chown -R docker /Users"
$ minishift ssh
$ sshfs <username>@<IP>:/Users/<username>/ /Users
----

. Verify the share mount.
+

----
$ minishift ssh "ls -al /Users/<username>"
----
