include::variables.adoc[]

= {project} Profiles
:icons:
:toc: macro
:toc-title:
:toclevels: 1

toc::[]

[[profile-overview]]
== Overview

A profile is an instance of the Minishift VM along with all of its configuration and state.
The profile feature allows you to create and manage these isolated instances of Minishift.

Each {project} profile is created with its own configuration (memory, CPU, disk size, add-ons, and so on) and is independent of other profiles.
Refer to the use of xref:../using/basic-usage.adoc#environment-variables[environment variables] if you want to make sure that certain configuration settings, for example `cpus` or `memory`, get applied to all profiles.

The _active_ profile is the profile against which all commands are executed, unless the global `--profile` flag is used.
You can determine the active profile by using the xref:../command-ref/minishift_profile_list.adoc#[`minishift profile list`] command.
You can execute single commands against a non-active profile by using the `--profile` flag, for example `minishift --profile profile-demo console` to open the OpenShift console for the specified *profile-demo* profile.

On top of the `--profile` flag, there are xref:../command-ref/minishift_profile.adoc#[commands] for xref:../command-ref/minishift_profile_list.adoc#[listing], xref:../command-ref/minishift_profile_delete.adoc#[deleting] and xref:../command-ref/minishift_profile_set.adoc#[setting] the active profile.
These commands are described in the following sections.

[WARNING]
====
Even though profiles are independent of each other, they share the same cache for ISOs, `oc` binaries and container images.
`minishift delete --clear-cache` will for this reason affect all profiles.
We recommend using `--clear-cache` with caution.
====

[[creating-profiles]]
== Creating Profiles

There are two ways to create a new profile.

[NOTE]
====
Profile name can only consist of alphanumeric characters.
The use of underscore ( *_* ) and hyphen ( *-* ) are allowed as separator.
====

=== Using the `--profile` Flag

When you run {project} `start` command with the `--profile` flag the profile gets created if it does not exist, for example:

----
$ minishift --profile profile-demo start
-- Checking if requested hypervisor 'xhyve' is supported on this platform ... OK
-- Checking if xhyve driver is installed ...
   Driver is available at /usr/local/bin/docker-machine-driver-xhyve
   Checking for setuid bit ... OK
-- Checking the ISO URL ... OK
-- Starting local OpenShift cluster using 'xhyve' hypervisor ...
-- Minishift VM will be configured with ...
   Memory:    2 GB
   vCPUs :    2
   Disk size: 20 GB
...
----

See also xref:../using/profiles.adoc#example-workflow-profile-config[workflow for profile configuration].

[NOTE]
====
A profile automatically becomes the active profile when a {project} instance is started successfully via `minishift start`.
====

=== Using the `profile set` Command

The other option to create a profile is to use the `profile set` command.
If the specified profile does not exist, it is implicitly created:

----
$ minishift profile set demo
Profile 'demo' set as active profile
----

[NOTE]
====
The default profile is *minishift*.
It will be present by default and it does not need to be created.
====

[[listing-profiles]]
== Listing Profiles

You can list all existing profiles with the xref:../command-ref/minishift_profile_list.adoc#[`minishift profile list`] command.
You can also see the active profile highlighted in the output.

----
$ minishift profile list
- minishift     Running     	(Active)
- profile-demo  Does Not Exist
----

[[switching-profiles]]
== Switching Profiles

To switch between profiles use the xref:../command-ref/minishift_profile_set.adoc#[`minishift profile set`] command:

----
$ minishift profile set profile-demo
Profile 'profile-demo' set as active profile
----

[NOTE]
====
Only one profile can be active at any time.
====

[[deleting-profiles]]
== Deleting Profiles

To delete a profile, run:

----
$ minishift profile delete profile-demo
You are deleting the active profile. It will remove the VM and all related artifacts. Do you want to continue [y/N]?: y
Deleted:  /Users/john/.minishift/profiles/profile-demo
Profile 'profile-demo' deleted successfully
Switching to default profile 'minishift' as the active profile.
----

[NOTE]
====
The default profile *minishift* cannot be deleted.
====

[[example-workflow-profile-config]]
== Example Workflow for Profile Configuration

You have two options to create a new profile and configure its xref:../using/basic-usage.adoc#persistent-configuration[persistent configuration].
The first option is to implicitly create the new profile by making it the active profile using the `profile set` command.
Once the profile is active you can run any `minishift config` command.
Lastly, start the instance:

----
$ minishift profile set profile-demo
$ minishift config set memory 8GB
$ minishift config set cpus 4
$ minishift addon enable anyuid
$ minishift start
----

The alternative is to execute a series of commands each specifying the targeted profile explicitly using the `--profile` flag:

----
$ minishift --profile profile-demo config set memory 8GB
$ minishift --profile profile-demo config set cpus 4
$ minishift --profile profile-demo addon enable anyuid
$ minishift --profile profile-demo minishift start
----
