[[reusing-docker-daemon]]
= Reusing the Docker daemon
:icons:
:toc: macro
:toc-title:
:toclevels: 1

toc::[]

When running OpenShift in a single VM, it is recommended to reuse the
Docker daemon that Minishift uses for pure Docker use-cases as well. By
using the same docker daemon as Minishift, you can speed up your local
experiments.

.  Make sure that you have the Docker client binary installed on your
machine. For information about specific binary installations for your
operating system, see the
https://docs.docker.com/engine/installation/[Docker installation] site.

.  Start Minishift with the link:../command-ref/minishift_start{outfilesuffix}[`minishift start`] command.

.  Use the link:../command-ref/minishift_docker-env{outfilesuffix}[`minishift docker-env`] command
to export the environment variables that are required to reuse the daemon.
+
----
eval $(minishift docker-env)
----
+
You should now be able to use _docker_ on the command line of your host,
talking to the docker daemon inside the Minishift VM.

.  To test the connection, run the following command:
+
----
docker ps
----
+
If successful, the shell will print a list of running containers.
