= Troubleshooting Minishift
:icons:
:toc: macro
:toc-title:
:toclevels: 1

toc::[]

[[troubleshooting-overview]]
== Overview

This section contains solutions to common problems that you might encounter while using Minishift.

[[minshift-update-failed-due-to-permission-denied]]
== Permission denied error when updating Minishift

When updating Minishift using `minishift update`, the update process needs write permissions for the Minishift binary as well as the directory in which it is located.
Without these permisions `minishift update` will fail.
For example, this issue might occur when installing Minishift as root.

Workaround: When updating minishift, use `sudo minishift update` (Linux/macOS).

----
$ which minishift
/usr/bin/minishift

$ minishift update
A newer version of minishift is available.
Do you want to update from 1.1.0 to 1.2.0 now? [y/N]: y
Downloading https://github.com/minishift/minishift/releases/download/v1.2.0/minishift-1.2.0-linux-amd64.tgz
 3.68 MiB / 3.68 MiB [===========================================================================================================================================] 100.00% 0s
 65 B / 65 B [===================================================================================================================================================] 100.00% 0s
Update failed: open /usr/bin/.minishift.new: permission denied
----

[[special-characters-passwords]]
== Special characters cause passwords to fail

Depending on your operating system and shell environment, certain special characters can trigger variable interpolation and therefore cause passwords to fail.

Workaround: When creating and entering passwords, wrap the string with single quotes in the following format: `'<password>'`

[[minishift-delete-fails-undefine-snapshots]]
== Undefining virsh snapshots fail

If you use `virsh` on KVM/libvirt to create snapshots in your development workflow, and then use `minishift delete` to delete the snapshots along with the VM, you might encounter the following error:

----
$ minishift delete
Deleting the Minishift VM...
Error deleting the VM:  [Code-55] [Domain-10] Requested operation is not valid: cannot delete inactive domain with 4 snapshots
----

Cause: The snapshots are stored in *_~/.minishift/machines_*, but the definitions are stored in *_var/lib/libvirt/qemu/snapshot/minishift_*.

Workaround: To delete the snapshots, you need to perform the following steps.

.  Delete the definitions.
+

----
$ sudo virsh snapshot-delete --metadata minishift <snapshot-name>
----

.  Undefine the Minishift domain.
+

----
$ sudo virsh undefine minishift
----
+

You can now run `minishft delete` to delete the VM and restart Minishift.

[NOTE]
====
If these steps do not resolve the issue, you can also use the following command to delete the snapshots:

----
$ rm -rf ~/.minishift/machines
----
====

It is recommended to avoid using metadata when you create snapshots.
To ensure this, you can specify the `--no-metadata` flag.
For example:

----
$ sudo virsh snapshot-create-as --domain vm1 overlay1 --diskspec vda,file=/export/overlay1.qcow2 --disk-only --atomic --no-metadata
----

[[dial-tcp-missing-address]]
== KVM: Error creating new host: dial tcp: missing address

The problem is likely that the *libvirtd* service is not running.
You can check this with the following command:

----
$ systemctl status libvirtd
----

If *libvirtd* is not running, start it and enable it to start on boot:

----
$ systemctl start libvirtd
$ systemctl enable libvirtd
----

[[fail-connect-socket]]
== KVM: Failed to connect socket to '/var/run/libvirt/virtlogd-sock'

The problem is likely that the *virtlogd* service is not running.
You can check this with the following command:

----
$ systemctl status virtlogd
----

If *virtlogd* is not running, start it and enable it to start on boot:

----
$ systemctl start virtlogd
$ systemctl enable virtlogd
----

[[domain-minishift-already-exists]]
== KVM: Domain 'minishift' already exists...

If you try `minishift start` and the this error appears, ensure that you use `minishift delete` to delete the VMs that you created earlier.
However, if this fails and you want to completely clean up Minishift and start fresh, do the following:

. Check if any existing Minishift VM are running:
+

----
$ sudo virsh list --all
----

. If any Minishift VM is running, stop it:
+

----
$ sudo virsh destroy minishift
----

. Delete the VM:
+

----
$ sudo virsh undefine minishift
----

. Delete the *_.minishift/machines_* directory:
+

----
 $ rm -rf ~/.minishift/machines
----

In case all of this fails, you might want to xref:../getting-started/uninstalling.adoc#[uninstall Minishift] and do a fresh install of Minishift.

[[create-vmnet-interface-permission]]
== xhyve: Could not create vmnet interface

The problem is likely that the xhyve driver is not able to clean up *vmnet* when a VM is removed.
*vmnet.framework* determines the IP address based on the following files:

* *_/var/db/dhcpd_leases_*
* *_/Library/Preferences/SystemConfiguration/com.apple.vmnet.plist_*

Reset the Minishift-specific IP database, ensure that you remove the `minishift` entry section from the `dhcpd_leases` file, and reboot your system.

----
{
  ip_address=192.168.64.2
  hw_address=1,2:51:8:22:87:a6
  identifier=1,2:51:8:22:87:a6
  lease=0x585e6e70
  name=minishift
}
----

NOTE: You can completely reset the IP database by removing the files manually but this is very risky.

[[machine-doesnt-exist]]
== VirtualBox: Error machine does not exist

If you use Windows, ensure that you set the `--vm-driver virtualbox` flag in the `minishift start` command.
Alternatively, the problem might be an outdated version of VirtualBox.

To avoid this issue, it is recommended to use VirtualBox 5.1.12 or later.

[[insufficient-privileges]]
== Hyper-V: Hyper-V commands must be run as an Administrator

If you run Minishift with Hyper-V on Windows as a normal user or as a user with Administrator privileges, you might encounter the following error:

----
Error starting the VM: Error creating the VM. Error with pre-create check: "Hyper-V commands must be run as an Administrator".
----

Workaround: You can either add yourself to the Hyper-V Administrators group, which is recommended, or run the shell in an elevated mode.

If you are using PowerShell, you can add yourself to the Hyper-V Administrators group as follows:

. As an administrator, run the following command:
+
----
([adsi]”WinNT://./Hyper-V Administrators,group”).Add(“WinNT://$env:UserDomain/$env:Username,user”)
----

. Log out and log back in for the change to take effect.

You can also use the GUI to add yourself to the Hyper-V Administrators group as follows:

. Click the *Start* button and choose *Computer Management*.
. In the *Computer Management* window, select *Local Users And Groups* and then double click on *Groups*.
. Double click on the *Hyper-V Administrators* group, the *Hyper-V Administrators Properties* dialog box is displayed.
. Add your account to the Hyper-V Administrators group and log off and log in for the change to take effect.

Now you can run the Hyper-V commands as a normal user.

For more options for Hyper-V see link:https://blogs.msdn.microsoft.com/virtual_pc_guy/2010/09/28/creating-a-hyper-v-administrators-local-group-through-powershell[creating Hyper-V administrators local group].

[[hyperv-fails-openvpn]]
== Hyper-V: Minishift running with Hyper-V fails when connected to OpenVPN

If you try to use Minishift with Hyper-V using an external virtual switch while you are connected to a VPN such as OpenVPN, Minishift might fail to provision the VM.

Cause: Hyper-V networking might not route the network traffic in both directions properly when connected to a VPN.

Workaround: Disconnect from the VPN and try again after stopping the VM from the Hyper-V manager.

[[root-filesystem-exceeds-overlay-size]]
== The root filesystem of the Minishift VM exceeds overlay size

Installing additional packages or copying large files to the root filesystem of the Minishift VM might exceed the allocated overlay size and lock the Minishift VM.

Cause: The Minishift VM root filesystem contains core packages that are configured to optimize running the Minishift VM and containers.
The available storage on the root filesystem is determined by the overlay size, which is smaller than the total available storage.

Workaround: Avoid installing packages or storing large files in the root filesystem of the Minishift VM.
Instead, you can create a sub-directory in the *_mnt/sda1/_* persistent storage volume or define and mount xref:../using/host-folders.adoc#[host folders] that can share storage space between the host and the Minishift VM.

If you want to perform development tasks inside the Minishift VM, it is recommended that you use containers, which are stored in persistent storage volumes, and reuse the xref:../using/docker-daemon.adoc#[Minishift Docker daemon].


[[minshift-startup-check-failed]]
== Minishift startup check failed

While Minishift starts, it runs several startup checks to make sure that the Minishift VM and the OpenShift Cluster are able to start without any issues.
If any configuration is incorrect or missing, the startup checks fail and Minishift does not start.

The following sections describe the different startup checks.

[[driver-plugin-check]]
=== Driver plug-in configuration

One of the startup checks verifies that the relevant driver plug-in is configured correctly.
If this startup check fails, review the xref:../getting-started/setting-up-driver-plugin.adoc#[setting up the driver plug-in] topic and configure the driver.

If you want to force Minishift to start despite a failing driver plugin-in check, you can instruct Minishift to treat these errors as warnings:

- For KVM/Libvirt on Linux, run the following command:
+
----
$ minishift config set warn-check-kvm-driver true
----

- For xhyve on macOS, run the following command:
+
----
$ minishift config set warn-check-xhyve-driver true
----

- For Hyper-V on Windows, run the following command:
+
----
$ minishift config set warn-check-hyperv-driver true
----

[[persistent-storage-check]]
=== Persistent storage volume configuration and usage

Minishift checks whether the persistent storage volume is mounted and that enough disk space is available.
If the persistent storage volume, for example, uses more than 95% of the available disk space, Minishift will not start.

If you want to recover the data, you can skip this test and start Minishift to access the persistent volume:

----
$ minishift config set skip-check-storage-usage true
----

[[external-network-check]]
=== External network connectivity

After the Minishift VM starts, it runs several network checks to verify whether external connectivity is possible from within the Minishift VM.

By default, network checks are configured to treat any errors as warnings, because of the diversity of the development environments.
You can configure the network checks to optimize them for your environment.

For example, one of the network checks pings an external host. You can change the host by running the following command:

----
$ minishift config set check-network-ping-host <host-IP-address>
----

Replace `<host-IP-address>` with the address of your internal DNS server, proxy host, or an external host that you can reach from your machine.

Because proxy connectivity might be problematic, you can run a check that tries to retrieve an external URL.
You can configure the URL by running:

----
$ minishift config set check-network-http-host <URL>
----

[[github-api-rate-limit-exceeded]]
== GitHub API rate limit exceeded

When you run `minishift start` or `minishift update`, it makes requests to GitHub API to check for new version and potentially download new versions of the Minishift or OpenShift client tool `oc`.

Sometimes, during these requests, you might receive a 403 forbidden status from GitHub if your request exceeds the rate limit for your IP address. In this case, the command will fail and you will receive an error message. For example:

----
Error starting the cluster: Error attempting to download and cache oc: Cannot get the OpenShift
release version v3.6.0: GET https://api.github.com/repos/openshift/origin/releases/tags/v3.6.0:
403 API rate limit exceeded for (your IP shows here). (But here's the good news: Authenticated
requests get a higher rate limit. Check out the documentation for more details.); rate reset in
17m2.462768522s
----

GitHub has a rate limiting policy, see link:https://developer.github.com/v3/#rate-limiting[Rate Limiting]. You may have reached this limit for various reasons. For example, your package manager may use GitHub API calls or you are behind a corporate network that makes a lot of GitHub unauthenticated API calls.

Instead of waiting for GitHub to reset the limit for your IP address, you can create a link:https://GitHub.com/blog/1509-personal-api-tokens[Personal API Tokens] from your GitHub account. This gives you a higher rate limit.

After you generate the API token, you need to set the `MINISHIFT_GITHUB_API_TOKEN` environment variable by running:

----
$ export MINISHIFT_GITHUB_API_TOKEN=<token_ID>
----

Replace `<token_ID>` with your token. You can also add this variable in your shell profile so you don't need to manually set the variable every time you run a Minishift command.