build:
  image: fedora:26
  tags:
    - docker
  script:
    - dnf install -y golang make git python
    - export CURRENT_BUILD_PATH=$PWD
    - mkdir -p $HOME/gopath/bin
    - curl -L https://github.com/golang/dep/releases/download/v0.4.1/dep-linux-amd64 -o $HOME/gopath/bin/dep
    - chmod +x $HOME/gopath/bin/dep
    - export GOPATH=$HOME/gopath
    - export PATH=$PATH:$GOPATH/bin
    - mkdir -p $HOME/gopath/src/github.com/minishift
    - ln -s $CURRENT_BUILD_PATH $HOME/gopath/src/github.com/minishift/minishift
    - cd $HOME/gopath/src/github.com/minishift/minishift/
    - make prerelease
    - rm -rf $HOME/gopath/src/github.com/minishift/minishift/out/bindata
    - mv $HOME/gopath/src/github.com/minishift/minishift/out/ $CURRENT_BUILD_PATH/public
  artifacts:
    paths:
      - public

