language: go
go:
- 1.7.1
install:
- mkdir /home/travis/gopath/bin
- mkdir /home/travis/gopath/pkg
- cd $HOME/gopath/src/github.com
- mv `ls` foo
- mv foo minishift
- cd minishift/minishift
- GLIDE_OS_ARCH=`go env GOHOSTOS`-`go env GOHOSTARCH`
- GLIDE_TAG=$(curl -s https://glide.sh/version)
- GLIDE_LATEST_RELEASE_URL="https://github.com/Masterminds/glide/releases/download/${GLIDE_TAG}/glide-${GLIDE_TAG}-${GLIDE_OS_ARCH}.tar.gz"
- wget ${GLIDE_LATEST_RELEASE_URL} -O /tmp/glide.tar.gz
- mkdir /tmp/glide
- tar --directory=/tmp/glide -xvf /tmp/glide.tar.gz
- export PATH=$PATH:/tmp/glide/${GLIDE_OS_ARCH}
script:
- make cross test fmtcheck prerelease
env:
  global:
  - secure: Ck8xVWqOVpReFaPoGjL4UCVnjOnbXE02zPTkFXlkkwsrv94z14kHSTwitWnHC+aX3jW/Y0oyyu4KhQfN58L2VV8X6WgciWiTOu687U6ITfrVvyAn9kB3gx3zPv1K+qLddwul7Ks5lX9+y/QNc4h1hf1kFBIznxvDq+lOjFeROyQF0r62/u7vF6t2AaM3TtWFm/Us4wXzb+lKPum7myyEyzxTs8PSxDiadye7Y1zeVInYq0ver7M4Z1cG8uEpFELeF5dvJmEje7R8lUcQAVvrrd3mN0IK3NZY+4MJZ9nVJK1EHwupqgNhgDmnX8QgiWOVNZVG0zNC6CpX8w29p3Ih3c5M13ejI1+6L30mEc8oTnDAaboidXXw00UIIo8miFpZi/jiypnLHqtH2MecFptEt+OJ0e2c0oa/MATJPkr3hF4WKsSxvz0P09bel3sztMK8hXmbCjx0R+nn937ty4L4KvzBFmpqFAC8zyaifTIdF89mDp3BVshxuQI6dHXESYgGTkVI8D/tAo5niR5Zn3kC8rxL9rO6juberq/9B8Ta1d4soiagrBBwrbuZF5rlvgU+yCkjTMAU3fZ5UIAhh1liePJ2rbo/i537vk0N6fkp180S0dCoo0ZVSF7mULeY0PVKjKe7Mk9meMXG93JTUYrwpNl7yMnErgVUrU58jQFWV3w=
