kind: ImageStreamList
apiVersion: v1
metadata:
  name: rhpam77-image-streams
  annotations:
    description: ImageStream definitions for Red Hat Process Automation Manager 7.7
    openshift.io/provider-display-name: Red Hat, Inc.
items:
- kind: ImageStream
  apiVersion: v1
  metadata:
    name: rhpam-businesscentral-rhel8
    annotations:
      openshift.io/display-name: Red Hat Process Automation Manager Business Central 7.7
      openshift.io/provider-display-name: Red Hat, Inc.
  spec:
    tags:
    - name: '7.7.0'
      annotations:
        description: Red Hat Process Automation Manager 7.7 - Business Central image.
        iconClass: icon-jboss
        tags: rhpam
        supports: rhpam:7.7
        version: '7.7.0'
      referencePolicy:
        type: Local
      from:
        kind: DockerImage
        name: registry.redhat.io/rhpam-7/rhpam-businesscentral-rhel8:7.7.0
    - name: '7.7.1'
      annotations:
        description: Red Hat Process Automation Manager 7.7 - Business Central image.
        iconClass: icon-jboss
        tags: rhpam
        supports: rhpam:7.7
        version: '7.7.1'
      referencePolicy:
        type: Local
      from:
        kind: DockerImage
        name: registry.redhat.io/rhpam-7/rhpam-businesscentral-rhel8:7.7.1
- kind: ImageStream
  apiVersion: v1
  metadata:
    name: rhpam-businesscentral-monitoring-rhel8
    annotations:
      openshift.io/display-name: Red Hat Process Automation Manager Business Central Monitoring 7.7
      openshift.io/provider-display-name: Red Hat, Inc.
  spec:
    tags:
    - name: '7.7.0'
      annotations:
        description: Red Hat Process Automation Manager 7.7 - Business Central Monitoring image.
        iconClass: icon-jboss
        tags: rhpam
        supports: rhpam:7.7
        version: '7.7.0'
      referencePolicy:
        type: Local
      from:
        kind: DockerImage
        name: registry.redhat.io/rhpam-7/rhpam-businesscentral-monitoring-rhel8:7.7.0
    - name: '7.7.1'
      annotations:
        description: Red Hat Process Automation Manager 7.7 - Business Central Monitoring image.
        iconClass: icon-jboss
        tags: rhpam
        supports: rhpam:7.7
        version: '7.7.1'
      referencePolicy:
        type: Local
      from:
        kind: DockerImage
        name: registry.redhat.io/rhpam-7/rhpam-businesscentral-monitoring-rhel8:7.7.1
- kind: ImageStream
  apiVersion: v1
  metadata:
    name: rhpam-controller-rhel8
    annotations:
      openshift.io/display-name: Red Hat Process Automation Manager Standalone Controller 7.7
      openshift.io/provider-display-name: Red Hat, Inc.
  spec:
    tags:
    - name: '7.7.0'
      annotations:
        description: Red Hat Process Automation Manager 7.7 - Standalone Controller image.
        iconClass: icon-jboss
        tags: rhpam
        supports: rhpam:7.7
        version: '7.7.0'
      referencePolicy:
        type: Local
      from:
        kind: DockerImage
        name: registry.redhat.io/rhpam-7/rhpam-controller-rhel8:7.7.0
    - name: '7.7.1'
      annotations:
        description: Red Hat Process Automation Manager 7.7 - Standalone Controller image.
        iconClass: icon-jboss
        tags: rhpam
        supports: rhpam:7.7
        version: '7.7.1'
      referencePolicy:
        type: Local
      from:
        kind: DockerImage
        name: registry.redhat.io/rhpam-7/rhpam-controller-rhel8:7.7.1
- kind: ImageStream
  apiVersion: v1
  metadata:
    name: rhpam-kieserver-rhel8
    annotations:
      openshift.io/display-name: Red Hat Process Automation Manager KIE Server 7.7
      openshift.io/provider-display-name: Red Hat, Inc.
  spec:
    tags:
    - name: '7.7.0'
      annotations:
        description: Red Hat Process Automation Manager 7.7 - KIE Server image.
        iconClass: icon-jboss
        tags: rhpam
        supports: rhpam:7.7
        version: '7.7.0'
      referencePolicy:
        type: Local
      from:
        kind: DockerImage
        name: registry.redhat.io/rhpam-7/rhpam-kieserver-rhel8:7.7.0
    - name: '7.7.1'
      annotations:
        description: Red Hat Process Automation Manager 7.7 - KIE Server image.
        iconClass: icon-jboss
        tags: rhpam
        supports: rhpam:7.7
        version: '7.7.1'
      referencePolicy:
        type: Local
      from:
        kind: DockerImage
        name: registry.redhat.io/rhpam-7/rhpam-kieserver-rhel8:7.7.1
- kind: ImageStream
  apiVersion: v1
  metadata:
    name: rhpam-smartrouter-rhel8
    annotations:
      openshift.io/display-name: Red Hat Process Automation Manager Smart Router 7.7
      openshift.io/provider-display-name: Red Hat, Inc.
  spec:
    tags:
    - name: '7.7.0'
      annotations:
        description: Red Hat Process Automation Manager 7.7 - Smart Router image.
        iconClass: icon-jboss
        tags: rhpam
        supports: rhpam:7.7
        version: '7.7.0'
      referencePolicy:
        type: Local
      from:
        kind: DockerImage
        name: registry.redhat.io/rhpam-7/rhpam-smartrouter-rhel8:7.7.0
    - name: '7.7.1'
      annotations:
        description: Red Hat Process Automation Manager 7.7 - Smart Router image.
        iconClass: icon-jboss
        tags: rhpam
        supports: rhpam:7.7
        version: '7.7.1'
      referencePolicy:
        type: Local
      from:
        kind: DockerImage
        name: registry.redhat.io/rhpam-7/rhpam-smartrouter-rhel8:7.7.1
- kind: ImageStream
  apiVersion: v1
  metadata:
    name: rhpam-process-migration-rhel8
    annotations:
      openshift.io/display-name: Red Hat Process Automation Manager Process Migration 7.7
      openshift.io/provider-display-name: Red Hat, Inc.
  spec:
    tags:
    - name: '7.7.0'
      annotations:
        description: Red Hat Process Automation Manager 7.7 - Process Migration image.
        iconClass: icon-jboss
        tags: rhpam
        supports: rhpam:7.7
        version: '7.7.0'
      referencePolicy:
        type: Local
      from:
        kind: DockerImage
        name: registry.redhat.io/rhpam-7/rhpam-process-migration-rhel8:7.7.0
    - name: '7.7.1'
      annotations:
        description: Red Hat Process Automation Manager 7.7 - Process Migration image.
        iconClass: icon-jboss
        tags: rhpam
        supports: rhpam:7.7
        version: '7.7.1'
      referencePolicy:
        type: Local
      from:
        kind: DockerImage
        name: registry.redhat.io/rhpam-7/rhpam-process-migration-rhel8:7.7.1
