include::variables.adoc[]

= Exposing Services
:icons:
:toc: macro
:toc-title:
:toclevels: 1

toc::[]

[[exposing-services-overview]]
== Overview

There are several ways you can expose your service after you deploy it on OpenShift.
The following sections describe the various methods and when to use them.

[[application-routes]]
== Routes

If you are deploying a Web application, the most common way to expose it is by a link:https://docs.openshift.org/latest/dev_guide/routes.html[route].
A route exposes the service as a host name.
You can create a route using the Web console or the CLI:

----
oc expose svc/frontend --hostname=www.example.com
----

To see a full example of creating an application and exposing it with a route, see the xref:../getting-started/quickstart.adoc#deploy-sample-app[{project} Quickstart] section.

[[nodeport-services]]
== NodePort Services

In case the service you want to expose is not HTTP based, you can create a link:https://docs.openshift.org/latest/architecture/core_concepts/pods_and_services.html#service-nodeport[*NodePort*] service.
In this case, each OpenShift node will proxy that port into your service.
To access this port on your {project} VM, you need to configure an link:https://docs.openshift.org/latest/dev_guide/expose_service/expose_internal_ip_nodeport.html[Ingress IP] using `oc expose` with the parameter `type=LoadBalancer`.

A common use-case for Ingress IP Self-Service is the ability to expose a database service.
The following example shows the complete workflow to create and expose a link:https://mariadb.org[MariaDB] instance using {project}:

----
$ minishift start
$ eval $(minishift oc-env)
$ oc new-app -e MYSQL_ROOT_PASSWORD=admin https://raw.githubusercontent.com/openshift/origin/master/examples/db-templates/mariadb-persistent-template.json
$ oc rollout status -w dc/mariadb
$ oc expose dc mariadb --type=LoadBalancer --name=mariadb-ingress
$ oc export svc mariadb-ingress
 ....
ports:
    - nodePort: 30907
 ....
----

After the service is exposed, you can access MariaDB with the `mysql` CLI using the {project} VM IP and the exposed NodePort service.

----
$ mysql --user=root --password=admin --host=$(minishift ip) --port=30907
----

[[port-forwarding]]
== Port Forwarding

=== Using `oc port-forward`
If you want to quickly access a port of a specific pod of your cluster, you can also use the `oc port-forward` command of the xref:../openshift/openshift-client-binary.adoc#[OpenShift CLI].

----
$ oc port-forward POD [LOCAL_PORT:]REMOTE_PORT
----

=== Using VirtualBox tools
In case you're using the VirtualBox driver plugin there is another method you can use for port forwarding.
This method will allow for permanent port forwarding as well as for forwarding multiple ports at the same time.
This method requires you to set up a `nodePort` as outlined above.

If we go by the example above, we can do the following:

----
$ VBoxManage controlvm minishift natpf1 "mariadb,tcp,,3306,,30907"
----

This will allow us to communicate with the mariadb service on `localhost:3306` which might be convenient if you don't want to change default ports.
Additionally, an important advantage of this way of forwarding ports is that we can talk to a service as opposed to just a single pod.
