include::variables.adoc[]

= Using the OpenShift Client Binary (oc)
:icons:
:toc: macro
:toc-title:
:toclevels: 2

toc::[]

[[openShift-client-binary-overview]]
== Overview

The `minishift start` command creates an OpenShift cluster using the link:https://github.com/openshift/origin/blob/master/docs/cluster_up_down.md[cluster up] approach.
For this purpose it copies the *oc* binary onto your host.

The *oc* binary is located in the  *_~/.minishift/cache/oc/{openshift-version}_* directory, assuming that you use {project}'s default version of OpenShift.
You can add this binary to your `PATH` using xref:../command-ref/minishift_oc-env.adoc#[`minishift oc-env`], which displays the command you need to type into your shell.

The output of `minishift oc-env` differs depending on the operating system and the shell type.

----
$ minishift oc-env
export PATH="/Users/john/.minishift/cache/oc/v1.5.0:$PATH"
# Run this command to configure your shell:
# eval $(minishift oc-env)
----

[[minishift-oc-context]]
== {project} CLI Profile

As part of the `minishift start` command, a https://docs.openshift.org/latest/cli_reference/manage_cli_profiles.html[CLI profile] named *minishift* is also created.
This profile, also known as a _context_, contains the configuration to communicate with your OpenShift cluster.

{project} activates this context automatically, but if you need to switch back to it after, for example, logging into another OpenShift instance, you can run:

----
$ oc config use-context minishift
----

For an introduction to `oc` usage, see the link:https://docs.openshift.org/latest/cli_reference/get_started_cli.html[Get Started with the CLI] topic in the OpenShift documentation.

[[log-into-cluster]]
== Logging Into the Cluster

By default, `cluster up` uses link:https://docs.openshift.org/latest/install_config/configuring_authentication.html#AllowAllPasswordIdentityProvider[AllowAllPasswordIdentityProvider] to authenticate against the local cluster.
This means any non-empty user name and password can be used to login to the local cluster.

The recommended user name and password is `developer` and `developer`, respectively. This is because they are already assigned to the default project *myproject* and also can link:https://docs.openshift.org/latest/architecture/additional_concepts/authentication.html#authentication-impersonation[impersonate] the administrator.
This allows you to run administrator commands using the `--as system:admin` parameter.

To login as administrator, use the system account:

----
$ oc login -u system:admin
----

In this case, link:https://docs.openshift.org/latest/architecture/additional_concepts/authentication.html#api-authentication[client certificates] are used.
The certificates are stored in *_~/.kube/config_*.
The `cluster up` command installs the appropriate certificates as a part of the bootstrap.

[NOTE]
====
If you run the command `oc login -u system -p admin`, you will log in but not as an administrator.
Instead, you will be logged in as an unprivileged user with no particular rights.
====

To view the available login contexts, run:

----
$ oc config view
----

[[access-web-console]]
== Accessing the Web Console

To access the link:https://docs.openshift.org/latest/architecture/infrastructure_components/web_console.html[OpenShift Web console], you can run this command in a shell after starting {project} to get the URL of the Web console:

----
$ minishift console --url
----

Alternatively, after starting {project}, you can use the following command to directly open the console in a browser:

----
$ minishift console
----

[[access-openshift-services]]
== Accessing OpenShift Services

To access a service that is exposed with a route, run this command in a shell:

----
$ minishift openshift service [-n NAMESPACE] [--url] NAME
----

For more information refer also to xref:../openshift/exposing-services.adoc#[Exposing Services].

[[view-openshift-logs]]
== Viewing OpenShift Logs

To access OpenShift logs, run the `logs` command after starting {project}:

----
$ minishift logs
----

[[update-openshift-config]]
== Updating OpenShift Configuration

While OpenShift is running, you can view and change the master or the node configuration of your cluster.

To view the OpenShift master configuration file *_master-config.yaml_*, run the following command:

----
$ minishift openshift config view
----

To show the node configuration instead of the master configuration, specify the `target` flag.

For details about the `view` sub-command, see the xref:../command-ref/minishift_openshift_config_view.adoc#[minishift openshift config view] synopsis.

NOTE: After you update the OpenShift configuration, OpenShift will transparently restart.

[[example-config-cors]]
=== Example: Configuring cross-origin resource sharing

In this example, you configure link:https://en.wikipedia.org/wiki/Cross-origin_resource_sharing[cross-origin resource sharing] (CORS) by updating the OpenShift master configuration to allow additional IP addresses to request resources.

By default, OpenShift only allows cross-origin resource requests from the IP address of the cluster or from localhost.
This setting is stored in the `corsAllowedOrigins` property of the link:https://docs.openshift.org/latest/admin_guide/master_node_configuration.html#master-configuration-files[master configuration] file *_master-config.yaml_*.

To change the property value and allow cross-origin requests from all domains, run the following command:

----
$  minishift openshift config set --patch '{"corsAllowedOrigins": [".*"]}'
----

[NOTE]
====
If you get the error _The specified patch need to be a valid JSON._ when you run the above command, you need to modify the above command depending on your Operating System, your shell environment and its interpolation behavior.

For example, if you use PowerShell on Windows 7 or 10, modify the above command to:

----
$ minishift openshift config set --patch '{\"corsAllowedOrigins\": [\".*\"]}'
----

If you use Command Prompt you might need to use:

----
$ minishift openshift config set --patch "{\"corsAllowedOrigins\": [\".*\"]}"
----

====

[[example-change-openshift-routing-suffix]]
=== Example: Changing the OpenShift routing suffix

In this example, you change the OpenShift routing suffix in the master configuration.

If you use a static routing suffix, you can set the `routing-suffix` flag as part of the xref:../command-ref/minishift_start.adoc#[`minishift start`] command.
By default, {project} uses a dynamic routing prefix based on http://nip.io/[nip.io], in which the IP address of the VM is a part of the routing suffix, for example *192.168.99.103.nip.io*.

If you experience issues with *nip.io*, you can use http://xip.io/[xip.io], which is based on the same principles.

To set the routing suffix to *xip.io*, run the following command:

----
$ minishift openshift config set --patch '{"routingConfig": {"subdomain": "<IP-ADDRESS>.xip.io"}}'
----

Make sure to replace `IP-ADDRESS` in the above example with the IP address of your {project} VM.
You can retrieve the IP address by running the xref:../command-ref/minishift_ip.adoc#[`minishift ip`] command.
