include::variables.adoc[]

= Releasing {project}
:icons:
:toc: macro
:toc-title:
:toclevels: 2

toc::[]

[[releasing-overview]]
== Overview

The following sections describe how to release {project} either via automated job or manually.

[[preparing-github-milestone]]
== Preparing the GitHub Milestone

. Verify the milestone you want to release:
  - Move remaining open issues into the next milestone.
  - Review resolved/closed issues and make sure they are classified correctly.
  - Check and update the resolution of the issues.
  For example, issues with merged pull requests should be labeled as *resolution/done*.
. Close the milestone.

[[automated-release]]
== Automated Release

An automated release can be performed by triggering CI job as:

----
$ make ci_release API_KEY=<api-key> RELEASE_VERSION=<version>
----

where

  - `api-key` : {project} CentOS CI API key
  - `version` : The expected release version (without 'v'). For example, 1.0.0.

Once triggered you can follow the release process link:https://ci.centos.org/job/minishift-release/[here].

The automated release performs:

- xref:../contributing/releasing.adoc#cut-release[Cutting the Release]
- xref:../contributing/releasing.adoc#trigger-docs-build[Triggering the Documentation Build]
- xref:../contributing/releasing.adoc#post-release-tasks[Perform Post-Release Tasks]


[NOTE]
====
If the CI release job is failing for a known reason then you can skip the integration tests by changing the `SKIP_INTEGRATION_TEST` value to `true` in Makefile.
====

The systemtray bits needs to uploaded separately, which can be performed by triggering CI job as:

----
$ make ci_release_systemtray CIRCLECI_API_KEY=<api-key> RELEASE_VERSION=<version>
----

where

  - `api-key` : {project} Circle CI API key
  - `version` : The expected release version (without 'v'). For example, 1.0.0.

[[manaul-release]]
== Manual Release

[[release-prereqs]]
=== Prerequisites

- You must have a https://help.github.com/articles/creating-an-access-token-for-command-line-use[GitHub personal access token] defined in your environment as `GITHUB_ACCESS_TOKEN`.
- You must set the environment variable `GITHUB_USER` as _minishift_.
- To create the systemtray binaries, link:https://developer.apple.com/xcode[`Xcode`] must be installed.

[[cut-release]]
=== Cutting the Release

. Run the required checks:
+
----
$ make prerelease
----

. Bump the {project} version in the link:https://github.com/minishift/minishift/blob/master/Makefile[Makefile].

. Commit and push your changes with a message of the form `cut v1.0.0`.

. Create binaries and upload them to GitHub (this will also tag the release):
+
----
$ make release
----

[[trigger-docs-build]]
=== Triggering the Documentation Build

Use the following to trigger the documentation build:

----
$ export API_KEY=<api-key>
$ curl -H "$(curl --user minishift:$API_KEY 'https://ci.centos.org//crumbIssuer/api/xml?xpath=concat(//crumbRequestField,":",//crumb)')" -X POST https://ci.centos.org/job/minishift-docs/build --user "minishift:$API_KEY"
----

This will build link:http://artifacts.ci.centos.org/minishift/minishift/docs/latest/[minishift-adoc.tar], which will be consumed by *docs.okd.io* during the next nightly build.
For more information, see xref:../contributing/writing-docs.adoc#[Writing and Publishing {project} Documentation].

[[post-release-tasks]]
=== Post-Release Tasks

The systemtray bits also need to be uploaded to the release in Github.
Create {project} binaries with systemtray and upload them to Github. 
The following command works only in macOS, please refer to the xref:../contributing/releasing.adoc#release-prereqs[Prerequisites] for more information.

----
$ make release_systemtray
----

As part of the release process we also send a release announcement and edit the GitHub release page.

For the latter we usually add a categorized list of closed issues as well as some release highlights (most often taken from the release announcement).

If you have link:https://stedolan.github.io/jq/[`jq`] installed on your machine, you can use the link:https://github.com/minishift/minishift/blob/master/scripts/release/issue-list.sh[issue-list.sh] script to generate the Markdown needed for adding the issue list.
For example:

----
$ cd scripts/release
$ ./issue-list.sh -r minishift -m 9
----

[[updating-brew-cask]]
=== Updating the brew cask

To update the {project} cask manually, we need to do the following tasks:

. Fork the link:https://github.com/caskroom/homebrew-cask[homebrew-cask] repository and clone it locally if not already done.
. Update the link:https://github.com/caskroom/homebrew-cask/blob/master/Casks/minishift.rb[minishift.rb] file with the latest version, sha256sum and checkpoint.
. Push the changes to the forked repository.
. And finally open a pull request in the link:https://github.com/caskroom/homebrew-cask[homebrew-cask] repository.

You can also use the link:https://github.com/minishift/minishift/blob/master/scripts/release/brew-cask.sh[brew-cask.sh] script to update link:https://github.com/caskroom/homebrew-cask/blob/master/Casks/minishift.rb[minishift.rb] with the latest version information.
For example:

----
$ cd scripts/release
$ ./brew-cask.sh -r /path/to/homebrew-cask-repo -v 1.13.0
----
