include::variables.adoc[]

[[troubleshooting-general]]
= Troubleshooting Miscellaneous 
:icons:
:toc: macro
:toc-title:
:toclevels: 2

toc::[]

[[troubleshooting-general-overview]]
== Overview

This section contains solutions to common problems that you might encounter while using various components of {project}.

[[root-filesystem-exceeds-overlay-size]]
== The root filesystem of the {project} VM exceeds overlay size

Installing additional packages or copying large files to the root filesystem of the {project} VM might exceed the allocated overlay size and lock the {project} VM.

Cause: The {project} VM root filesystem contains core packages that are configured to optimize running the {project} VM and containers.
The available storage on the root filesystem is determined by the overlay size, which is smaller than the total available storage.

Workaround: Avoid installing packages or storing large files in the root filesystem of the {project} VM.
Instead, you can create a sub-directory in the *_/mnt/sda1/_* persistent storage volume or define and mount xref:../using/host-folders.adoc#[host folders] that can share storage space between the host and the {project} VM.

If you want to perform development tasks inside the {project} VM, it is recommended that you use containers, which are stored in persistent storage volumes, and reuse the xref:../using/docker-daemon.adoc#[{project} Docker daemon].

[[special-characters-passwords]]
== Special characters cause passwords to fail

Depending on your operating system and shell environment, certain special characters can trigger variable interpolation and therefore cause passwords to fail.

Workaround: When creating and entering passwords, wrap the string with single quotes in the following format: `'<password>'`
