include::variables.adoc[]

[[troubleshooting-general]]
= Troubleshooting Miscellaneous 
:icons:
:toc: macro
:toc-title:
:toclevels: 2

toc::[]

[[troubleshooting-general-overview]]
== Overview

This section contains solutions to common problems that you might encounter while using various components of {project}.

[[root-filesystem-exceeds-overlay-size]]
== The root filesystem of the {project} VM exceeds overlay size

Installing additional packages or copying large files to the root filesystem of the {project} VM might exceed the allocated overlay size and lock the {project} VM.

Cause: The {project} VM root filesystem contains core packages that are configured to optimize running the {project} VM and containers.
The available storage on the root filesystem is determined by the overlay size, which is smaller than the total available storage.

Workaround: Avoid installing packages or storing large files in the root filesystem of the {project} VM.
Instead, you can create a sub-directory in the *_/mnt/sda1/_* persistent storage volume or define and mount xref:../using/host-folders.adoc#[host folders] that can share storage space between the host and the {project} VM.

If you want to perform development tasks inside the {project} VM, it is recommended that you use containers, which are stored in persistent storage volumes, and reuse the xref:../using/docker-daemon.adoc#[{project} Docker daemon].

[[special-characters-passwords]]
== Special characters cause passwords to fail

Depending on your operating system and shell environment, certain special characters can trigger variable interpolation and therefore cause passwords to fail.

Workaround: When creating and entering passwords, wrap the string with single quotes in the following format: `'<password>'`


[[authentication-required-to-push-image]]
== Authentication required to push image to OpenShift integrated Docker registry

If you are using a Fedora, CentOS or RHEL host and you want to push to the OpenShift registry as described in xref:../openshift/openshift-docker-registry.adoc#[Accessing the OpenShift Docker Registry], you have to use the CentOS xref:../using/basic-usage.adoc#choosing-iso-image[ISO].
Using the Boot2Docker or Minikube xref:../using/basic-usage.adoc#choosing-iso-image[ISO] will result in the following authorization error:

----
$ docker login -u developer -p `oc whoami -t` 172.30.1.1:5000
Login Succeeded
$ docker pull busybox
$ docker tag busybox 172.30.1.1:5000/myproject/busybox:latest
$ docker push 172.30.1.1:5000/myproject/busybox:latest
The push refers to a repository [172.30.1.1:5000/myproject/busybox]
6a749002dd6a: Preparing 
unauthorized: authentication required
----

The reason is an incompatibility between the Docker client shipped with your host and the Docker daemon which is running inside the {project} VM.

Workaround: Use the xref:../using/basic-usage.adoc#choosing-iso-image[CentOS ISO] when using {project} on Fedora, CentOS or RHEL.
For example:

----
minishift start --iso-url centos
----

[[invalid-x509-certificate]]
== X.509 certificate is valid for 10.0.2.15, 127.0.0.1, 172.17.0.1, 172.30.0.1, 192.168.99.100, not 192.168.99.101

Starting a stopped {project} VM can produce the following X.509 certificate error:

----
$ minishift start
-- Checking if requested hypervisor 'kvm' is supported on this platform ... OK
-- Checking the ISO URL ... OK
-- Starting local OpenShift cluster using 'kvm' hypervisor ...
-- Starting Minishift VM ......................... OK
[...]
FAIL
   Error: cannot access master readiness URL https://192.168.99.101:8443/healthz/ready
   Details:
     No log available from "origin" container

   Caused By:
     Error: Get https://192.168.99.101:8443/healthz/ready: x509: certificate is valid for 10.0.2.15, 127.0.0.1, 172.17.0.1, 172.30.0.1, 192.168.99.100, not 192.168.99.101
Error during 'cluster up' execution: Error starting the cluster.
----

The reason for the above error is that OpenShift cluster certificates contain the IP of the {project} VM.
The certificates are generated only when {project} VM is freshly started.
After restart, the {project} VM might be assigned a new IP address and if this happens the certificate become invalid.

Workaround: Delete the existing {project} VM and start again.

----
$ minishift delete --force
$ minishift start
----

[[Remove-password-from-keychain]]
== Removing subscription password from OS native keychain

These steps only applies if you are using a subscription capable ISO image like Red Hat Enterprise Linux with {project}
which needs registration using username and password.

=== Windows

On Windows, the password is stored using *Credential Manager*.
Run the following command in Command Prompt to delete the stored password:

----
CMD> cmdkey /delete:minishift:<username>
----

=== Linux

On Linux, the feature needs to store the password using *D-Bus Secret Service API*, which is provided by *GNOME libsecret*.
Run the following command to delete the stored password:

----
$ secret-tool clear service minishift username <username>
----

=== macOS

On macOS, the password is stored using *Keychain Access*.
Run the following command to delete the stored password:

----
$ security delete-generic-password -s minishift
----
