# If you do not have OpenSSL installed, change
# the following line to use 'http://'
source 'https://rubygems.org'

# For faster file watcher updates on Windows:
gem 'wdm', '~> 0.1.0', platforms: [:mswin, :mingw]

# Windows does not come with time zone data
gem 'tzinfo-data', platforms: [:mswin, :mingw, :jruby]

# Middleman Gems
gem 'middleman', '~> 4.2'
gem 'middleman-livereload', '~> 3.4'
gem 'middleman-asciidoc'
gem 'middleman-syntax'
gem 'font-awesome-middleman'
gem 'redcarpet'
gem 'therubyracer'
