include::variables.adoc[]

[[installing-minishift]]
= Installing {project}
:icons:
:toc: macro
:toc-title:
:toclevels: 1

toc::[]

[[installing-manually]]
== Manually

. Download the archive for your operating system from the link:{download-url}[{download-text}] page and extract its contents.

. Copy the contents of the directory to your preferred location.

. Add the `minishift` binary to your `PATH` environment variable.

[NOTE]
====
- On the Windows operating system, due to issue link:https://github.com/minishift/minishift/issues/236[#236], you need to execute the {project} binary from your local *_C:\_* drive.
You cannot run {project} from a network drive.
- {project} will use any SSH binary found on the `PATH` in preference to internal SSH code.
Ensure that any SSH binary in the system `PATH` does not generate warning messages as this will cause installation problems such as issue  link:https://github.com/minishift/minishift/issues/1923[#1923].
====

[[installing-with-homebrew]]
== With Homebrew

On macOS, you can also use link:https://caskroom.github.io[Homebrew Cask] to install the stable version of {project}:

----
$ brew cask install minishift
----

To update the binary, run following command:

----
$ brew cask install --force minishift
----

== Next Steps

Proceed to the xref:../getting-started/quickstart.adoc#[{project} Quickstart] after installation.
