[[installing-minishift]]
= Installing Minishift
:icons:
:toc: macro
:toc-title:
:toclevels: 1

toc::[]

[[installing-overview]]
== Overview

The following section describes how to install Minishift and the required dependencies.

[[install-prerequisites]]
== Prerequisites

Minishift requires a hypervisor to start the virtual machine on which the OpenShift cluster is provisioned.
Verify that the hypervisor of your choice is installed and enabled on your system before you start Minishift.

Depending on your host operating system, you have the choice of the following hypervisors:

macOS::
- link:https://github.com/mist64/xhyve[xhyve] (default)
+
NOTE: xhyve requires specific installation and configuration steps that are described in the xref:../getting-started/setting-up-driver-plugin.adoc#[Setting Up the Driver Plug-in] section.

- link:https://www.virtualbox.org/wiki/Downloads[VirtualBox]
- link:https://www.vmware.com/products/fusion[VMware Fusion]

GNU/Linux::
- link:https://en.wikipedia.org/wiki/Kernel-based_Virtual_Machine[KVM] (default)
+
NOTE: KVM requires specific installation and configuration steps that are described in the xref:../getting-started/setting-up-driver-plugin.adoc#[Setting Up the Driver Plug-in] section.

- link:https://www.virtualbox.org/wiki/Downloads[VirtualBox]

Windows::
- link:https://docs.microsoft.com/en-us/virtualization/hyper-v-on-windows/quick-start/enable-hyper-v[Hyper-V] (default)
+
[NOTE]
====
To use Minishift with Hyper-V ensure that, after you link:https://docs.microsoft.com/en-us/virtualization/hyper-v-on-windows/quick-start/enable-hyper-v[install Hyper-V], you also link:https://docs.microsoft.com/en-us/virtualization/hyper-v-on-windows/quick-start/connect-to-network[add a Virtual Switch] using the Hyper-V Manager.
For specific configuration steps see the xref:../getting-started/setting-up-driver-plugin.adoc#[Setting Up the Driver Plug-in] section.
====

- link:https://www.virtualbox.org/wiki/Downloads[VirtualBox]
+
[NOTE]
====
It is recommended to use VirtualBox 5.1.12 or later on Windows to avoid the issue xref:../troubleshooting/troubleshooting-driver-plugins.adoc#machine-doesnt-exist[Error: machine does not exist].
If you encounter issues related to the hypervisor, see the xref:../troubleshooting/troubleshooting-driver-plugins.adoc#[Troubleshooting Driver Plug-ins] section.
====

[[installing-instructions]]
== Installing Minishift

=== Manually

.  Download the archive for your operating system from the link:https://github.com/minishift/minishift/releases[Minishift releases page] and unpack it.

.  Copy the contents of the directory to your preferred location.

.  Add the *minishift* binary to your `PATH` environment variable.

[NOTE]
====
- On Windows operating system, due to issue link:https://github.com/minishift/minishift/issues/236[#236], you need to execute the Minishift binary from your local C:/ drive.
You cannot run Minishift from a network drive.

- Automatic update of the Minishift binary and the virtual machine ISO is currently disabled.
See also issue link:https://github.com/minishift/minishift/issues/204[#204].
====

[[homebrew-install-minishift]]
=== With Homebrew

[[homebrew-stable-install]]
==== Stable

On macOS you can also use link:https://caskroom.github.io[Homebrew Cask] to install the stable version of Minishift:

----
  $ brew cask install minishift
----

[[homebrew-latest-install]]
==== Latest Beta

If you want to install the latest beta version of Minishift use the homebrew-cask versions tap.
After you install *homebrew-cask*, run the following command:

----
  $ brew tap caskroom/versions
----

You can now install the latest beta version of Minishift.

----
  $ brew cask install minishift-beta
----
