include::variables.adoc[]

[[quickstart]]
= Quickstart
:icons:
:toc: macro
:toc-title:
:toclevels: 1

toc::[]

[[quickstart-overview]]
== Overview

This section contains a brief demo of Minishift and of the provisioned
OpenShift cluster. For details on the usage of Minishift, see
the link:../using/managing-minishift{outfilesuffix}[Managing Minishift] section.

The interaction with OpenShift is with the command line tool _oc_ which
is copied to your host. For more information on how Minishift can assist
you in interacting with and configuring your local OpenShift instance
see the link:../using/interacting-with-openshift{outfilesuffix}[Interacting with OpenShift] section.

For more information about the OpenShift cluster architecture, see
https://docs.openshift.org/latest/architecture/index.html[Architecture Overview] in the OpenShift documentation.

[[basic-commands]]
== Basic Minishift commands

[[minishift-start-command]]
=== Minishift start

The link:../command-ref/minishift_start{outfilesuffix}[`minishift start`] command creates and
configures the Minishift VM and provisions a local, single-node
OpenShift instance within the VM.

The command also copies the `oc` binary to your host so that you can interact
with OpenShift through the `oc` command line tool or through the Web console,
which can be accessed through the URL provided in the output
of the `minishift start` command.

[[minishift-stop-command]]
=== Minishift stop

The link:../command-ref/minishift_stop{outfilesuffix}[`minishift stop`] command stops your OpenShift cluster and
shuts down the Minishift VM, but preserves the OpenShift cluster state.

Starting Minishift again will restore the OpenShift cluster, allowing
you to continue working from the last session. However, you must enter the same
parameters that you used in the original start command.

Efforts to further refine this experience are in progress. For details, see
the GitHub issue https://github.com/minishift/minishift/issues/179[#179].

[[minishift-delete-command]]
=== Minishift delete

The link:../command-ref/minishift_delete{outfilesuffix}[`minishift delete`] command deletes the OpenShift cluster,
and also shuts down and deletes the Minishift VM. No data or state are preserved.

[[networking]]
== Networking

The Minishift VM is exposed to the host system with a host-only IP address that
can be obtained with the `minishift ip` command.

[[starting-minishift]]
== Starting Minishift

The following steps describe how to get started with Minishift on a
GNU/Linux operating system with the KVM hypervisor driver.

.  Run the `minishift start` command.
+
----
$ minishift start
Starting local OpenShift cluster using 'kvm' hypervisor...
...
   OpenShift server started.
   The server is accessible via web console at:
       https://192.168.99.128:8443

   You are logged in as:
       User:     developer
       Password: developer

   To login as administrator:
       oc login -u system:admin
----
+
[NOTE]
====
- The IP is dynamically generated for each OpenShift cluster. To check
the IP, run the `minishift ip` command.
- By default, Minishift uses the driver most relevant to the host OS. To
use a different driver, set the `--vm-driver` flag in `minishift start`.
For example, to use VirtualBox instead of KVM on GNU/Linux operating
systems, run `minishift start --vm-driver=virtualbox`. For more
information about `minishift start` options, see the
https://minishift.io/docs/minishift_start.md[minishift start command
reference].
====

.  Add the `oc` binary to the _PATH_ environment variable.
+
[subs="verbatim,attributes"]
----
$ export PATH=$PATH:~/.minishift/cache/oc/{openshift-version}
----
+
NOTE: Depending on the operating system and the `oc` version, you
might need to use a different command to add `oc` to the _PATH_
environment variable. To verify the `oc` version, check the contents of
the `~/.minishift/cache/oc` directory.

For more information about interacting with OpenShift with the
command-line interface and the Web console, see the
link:../using/interacting-with-openshift{outfilesuffix}[Interacting with OpenShift] section.

[[deploy-sample-app]]
== Deploying an application

OpenShift provides various sample applications, such as templates,
builder applications, and quickstarts. The following steps describe how
to deploy a sample Node.js application from the command-line.

.  Create a Node.js example app.
+
----
$ oc new-app https://github.com/openshift/nodejs-ex -l name=myapp
----

.  Track the build log until the app is built and deployed.
+
----
$ oc logs -f bc/nodejs-ex
----

.  Expose a route to the service.
+
----
$ oc expose svc/nodejs-ex
----

.  Access the application.
+
----
$ minishift openshift service nodejs-ex -n myproject
----

.  To stop Minishift, use the following command:
+
----
$ minishift stop
Stopping local OpenShift cluster...
Stopping "minishift"...
----

For more information about creating applications in OpenShift, see
https://docs.openshift.org/latest/dev_guide/application_lifecycle/new_app.html[Creating New Applications] in the OpenShift documentation.
