include::variables.adoc[]

[[quickstart]]
= Minishift Quickstart
:icons:
:toc: macro
:toc-title:
:toclevels: 1

toc::[]

[[quickstart-overview]]
== Overview

This section contains a brief demo of Minishift and of the provisioned OpenShift cluster.
For details on the usage of Minishift, see the xref:../using/managing-minishift.adoc#[Managing Minishift] section.

The interaction with OpenShift is with the command-line tool _oc_ which is copied to your host.
For more information on how Minishift can assist you in interacting with and configuring your local OpenShift instance, see the xref:../openshift/openshift-client-binary.adoc#[OpenShift Client Binary] section.

For more information about the OpenShift cluster architecture, see link:https://docs.openshift.org/latest/architecture/index.html[Architecture Overview] in the OpenShift documentation.

The following steps describe how to get started with Minishift on a GNU/Linux operating system with the KVM hypervisor driver.

[[starting-minishift]]
== Starting Minishift

. Run the `minishift start` command.
+
----
$ minishift start
Starting local OpenShift cluster using 'kvm' hypervisor...
...
   OpenShift server started.
   The server is accessible via web console at:
       https://192.168.99.128:8443

   You are logged in as:
       User:     developer
       Password: developer

   To login as administrator:
       oc login -u system:admin
----
+
[NOTE]
====
- The IP is dynamically generated for each OpenShift cluster.
To check the IP, run the `minishift ip` command.
- By default, Minishift uses the driver most relevant to the host OS.
To use a different driver, set the `--vm-driver` flag in `minishift start`.
For example, to use VirtualBox instead of KVM on GNU/Linux operating systems, run `minishift start --vm-driver=virtualbox`.
For more information about `minishift start` options, see the xref:../command-ref/minishift_start.adoc#[`minishift start`] command.
====

. Use xref:../command-ref/minishift_oc-env.adoc#[`minishift oc-env`] to display the command you need to type into your shell in order to add the *oc* binary to your `PATH` environment variable.
The output of `oc-env` will differ depending on OS and shell type.
+
----
$ minishift oc-env
export PATH="/Users/john/.minishift/cache/oc/v1.5.0:$PATH"
# Run this command to configure your shell:
# eval $(minishift oc-env)
----

For more information about interacting with OpenShift with the command-line interface and the Web console, see the xref:../openshift/openshift-client-binary.adoc#[OpenShift Client Binary] section.

[[deploy-sample-app]]
== Deploying a Sample Application

OpenShift provides various sample applications, such as templates, builder applications, and quickstarts.
The following steps describe how to deploy a sample Node.js application from the command-line.

.  Create a Node.js example app.
+
----
$ oc new-app https://github.com/openshift/nodejs-ex -l name=myapp
----

.  Track the build log until the app is built and deployed.
+
----
$ oc logs -f bc/nodejs-ex
----

.  Expose a route to the service.
+
----
$ oc expose svc/nodejs-ex
----

.  Access the application.
+
----
$ minishift openshift service nodejs-ex --in-browser
----

.  To stop Minishift, use the following command:
+
----
$ minishift stop
Stopping local OpenShift cluster...
Stopping "minishift"...
----

For more information about creating applications in OpenShift, see link:https://docs.openshift.org/latest/dev_guide/application_lifecycle/new_app.html[Creating New Applications] in the OpenShift documentation.
