include::variables.adoc[]

[[quickstart]]
= Quickstart
:icons:
:toc: macro
:toc-title:
:toclevels: 1

toc::[]

[[quickstart-overview]]
== Overview

This section contains a brief demo of Minishift and of the provisioned
OpenShift cluster. For details on the usage of Minishift, see
the link:../using/managing-minishift{outfilesuffix}[Managing Minishift] section.

The interaction with OpenShift is with the command line tool _oc_ which
is copied to your host. For more information on how Minishift can assist
you in interacting with and configuring your local OpenShift instance
see the link:../using/interacting-with-openshift{outfilesuffix}[Interacting with OpenShift] section.

For more information about the OpenShift cluster architecture, see
https://docs.openshift.org/latest/architecture/index.html[Architecture Overview] in the OpenShift documentation.

The following steps describe how to get started with Minishift on a
GNU/Linux operating system with the KVM hypervisor driver.

[[starting-minishift]]
== Starting Minishift

. Run the `minishift start` command.
+
----
$ minishift start
Starting local OpenShift cluster using 'kvm' hypervisor...
...
   OpenShift server started.
   The server is accessible via web console at:
       https://192.168.99.128:8443

   You are logged in as:
       User:     developer
       Password: developer

   To login as administrator:
       oc login -u system:admin
----
+
[NOTE]
====
- The IP is dynamically generated for each OpenShift cluster. To check
the IP, run the `minishift ip` command.
- By default, Minishift uses the driver most relevant to the host OS. To
use a different driver, set the `--vm-driver` flag in `minishift start`.
For example, to use VirtualBox instead of KVM on GNU/Linux operating
systems, run `minishift start --vm-driver=virtualbox`. For more
information about `minishift start` options, see the
link:../command-ref/minishift_start{outfilesuffix}[`minishift start`] command.
====

. Use link:../command-ref/minishift_oc-env{outfilesuffix}[`minishift oc-env`] to display the command you need to type into your shell in order to add the _oc_ binary to your PATH.
The output of `oc-env` will differ depending on OS and shell type.
+
----
$ minishift oc-env
export PATH="/Users/john/.minishift/cache/oc/v1.5.0:$PATH"
# Run this command to configure your shell:
# eval $(minishift oc-env)
----

For more information about interacting with OpenShift with the
command-line interface and the Web console, see the
link:../using/interacting-with-openshift{outfilesuffix}[Interacting with OpenShift] section.

[[deploy-sample-app]]
== Deploying an application

OpenShift provides various sample applications, such as templates,
builder applications, and quickstarts. The following steps describe how
to deploy a sample Node.js application from the command-line.

.  Create a Node.js example app.
+
----
$ oc new-app https://github.com/openshift/nodejs-ex -l name=myapp
----

.  Track the build log until the app is built and deployed.
+
----
$ oc logs -f bc/nodejs-ex
----

.  Expose a route to the service.
+
----
$ oc expose svc/nodejs-ex
----

.  Access the application.
+
----
$ minishift openshift service nodejs-ex -n myproject
----

.  To stop Minishift, use the following command:
+
----
$ minishift stop
Stopping local OpenShift cluster...
Stopping "minishift"...
----

For more information about creating applications in OpenShift, see
https://docs.openshift.org/latest/dev_guide/application_lifecycle/new_app.html[Creating New Applications] in the OpenShift documentation.
