include::variables.adoc[]

[[setup-virtualization-environment]]
= Setting Up the Virtualization Environment
:icons:
:toc: macro
:toc-title:
:toclevels: 1
:next-steps: Proceed to xref:../getting-started/installing.adoc#[Installing {project}] once your hypervisor has been installed and configured.

toc::[]

[[setup-virtualization-environment-overview]]
== Overview

Follow the appropriate procedure to set up the hypervisor for your particular operating system.
{project} uses link:https://github.com/docker/machine/tree/master/libmachine[libmachine] and its driver plug-in architecture to provide a consistent way to manage the {project} VM.

Some hypervisors require manual installation of the driver plug-in.
{project} embeds the VirtualBox driver plug-in, so no additional steps are required to configure it.
However, VirtualBox will need to be identified to {project} via the `--vm-driver virtualbox` flag or persistent configuration settings.
See xref:setting-up-virtualbox-driver[Setting Up {project} to Use VirtualBox] for more information.

See the appropriate section for your hypervisor and operating system:

- For xref:for-linux[Linux], xref:setting-up-kvm-driver[set up the KVM driver]
- For xref:for-macos[macOS], xref:setting-up-hyperkit-driver[set up the hyperkit driver]
- For xref:for-windows[Windows], xref:setting-up-hyper-v-driver[set up the Hyper-V driver]
- For VirtualBox, xref:setting-up-virtualbox-driver[set up {project} to use VirtualBox]

[[for-linux]]
== Linux

[[setting-up-kvm-driver]]
=== Setting Up the KVM Driver

{project} is currently tested against `docker-machine-driver-kvm` version 0.10.0.

Proceed to the instructions for your Linux distribution after you have set up the `docker-machine-driver-kvm` binary.

For more information, see the GitHub documentation of the link:https://github.com/dhiltgen/docker-machine-kvm#quick-start-instructions[Docker Machine KVM driver].

[[kvm-driver-ubuntu]]
=== On Ubuntu

.  Install *libvirt* and *qemu-kvm* on your system:
- For Ubuntu-18.10
+
----
$ sudo apt install qemu-kvm libvirt-daemon libvirt-daemon-system
----
- For older Ubuntu versions
+
----
$ sudo apt install libvirt-bin qemu-kvm
----

.  Add yourself to the *libvirt(d)* group:
- For Ubuntu-18.10
+
----
$ sudo usermod -a -G libvirt $(whoami)
----
- For older Ubuntu versions
+
----
$ sudo usermod -a -G libvirtd $(whoami)
----

.  Update your current session to apply the group change:
- For Ubuntu-18.10
+
----
$ newgrp libvirt
----
- For older Ubuntu versions
+
----
$ newgrp libvirtd
----

. As root, install the KVM driver binary and make it executable as follows:
- For Ubuntu-16.04 and higher
+
----
# curl -L https://github.com/dhiltgen/docker-machine-kvm/releases/download/v0.10.0/docker-machine-driver-kvm-ubuntu16.04 -o /usr/local/bin/docker-machine-driver-kvm
# chmod +x /usr/local/bin/docker-machine-driver-kvm
----

- For Ubuntu-14.04
+
----
# curl -L https://github.com/dhiltgen/docker-machine-kvm/releases/download/v0.10.0/docker-machine-driver-kvm-ubuntu14.04 -o /usr/local/bin/docker-machine-driver-kvm
# chmod +x /usr/local/bin/docker-machine-driver-kvm
----

[[kvm-driver-fedora]]
=== On Fedora

.  Install *libvirt* and *qemu-kvm* on your system:
+
----
$ sudo dnf install libvirt qemu-kvm
----

.  Add yourself to the *libvirt* group:
+
----
$ sudo usermod -a -G libvirt $(whoami)
----

.  Update your current session to apply the group change:
+
----
$ newgrp libvirt
----

. As root, install the KVM driver binary and make it executable as follows:
+
----
# curl -L https://github.com/dhiltgen/docker-machine-kvm/releases/download/v0.10.0/docker-machine-driver-kvm-centos7 -o /usr/local/bin/docker-machine-driver-kvm
# chmod +x /usr/local/bin/docker-machine-driver-kvm
----

[[kvm-driver-arch-linux]]
=== On Arch Linux

. Install *libvirt*, *qemu*, *dnsmasq* and *ebtables* on your system:
+
----
$ sudo pacman -S libvirt qemu dnsmasq ebtables
----

. Add yourself to the *kvm* and *libvirt* groups:
+
----
$ sudo usermod -a -G kvm,libvirt $(whoami)
----

. Update the *libvirt* configuration in *_/etc/libvirt/qemu.conf_* as follows:
+
----
$ sudo sed -ri 's/.?group\s?=\s?".+"/group = "kvm"/1' /etc/libvirt/qemu.conf
----

. Update your current session to apply the group change:
+
----
$ newgrp libvirt
----

. As root, install the KVM driver binary and make it executable as follows:
+
----
# curl -L https://github.com/dhiltgen/docker-machine-kvm/releases/download/v0.10.0/docker-machine-driver-kvm-centos7 -o /usr/local/bin/docker-machine-driver-kvm
# chmod +x /usr/local/bin/docker-machine-driver-kvm
----

[[kvm-driver-libvirtd-service]]
=== Start libvirtd service

. Check the status of **libvirtd**:

----
$ systemctl is-active libvirtd
----

. If **libvirtd** is not active, start the **libvirtd** service:

----
$ sudo systemctl start libvirtd
----

[[kvm-driver-networking]]
=== Configure libvirt networking

Some distributions set up the *default* libvirt network for you, while on others this might have to be done manually.

. Check your network status:
+
----
$ sudo virsh net-list --all
Name                 State      Autostart     Persistent
---------------------------------------------------------
default              active     yes           yes
----
If your output looks like the above then you're done.
However, if `State` is not `active` or `Autostart` is not `yes` you'll need to follow the steps below.

. Start the *default* libvirt network:
+
----
$ sudo virsh net-start default
----

. Now mark the *default* network as autostart:
+
----
$ sudo virsh net-autostart default
----

=== Next Steps

{next-steps}

[[for-macos]]
== macOS

[[setting-up-hyperkit-driver]]
=== Setting Up the hyperkit Driver

{project} is currently tested against *docker-machine-driver-hyperkit* version 1.0.0.

Using hyperkit requires having both `hyperkit` and `docker-machine-driver-hyperkit` installed

==== Installing hyperkit

* If you have link:https://docs.docker.com/docker-for-mac/[Docker Desktop for macOS] installed, `hyperkit` is already installed. 
* If you use link:https://brew.sh[Homebrew] you can install the latest version of `hyperkit`:

----
$ brew install hyperkit
----

==== Installing docker-machine-driver-hyperkit

* If you use link:https://brew.sh[Homebrew] you can install the latest version of `docker-machine-driver-hyperkit`:

----
$ brew install docker-machine-driver-hyperkit
----

* Alternatively, you can download and install the *docker-machine-driver-hyperkit* binary and place it in a directory which is on your `PATH` environment variable. The directory *_/usr/local/bin_* is a good choice, since it is the default installation directory for Docker Machine binaries.

The following steps explain the installation of the *docker-machine-driver-hyperkit* binary to the *_/usr/local/bin/_* directory:

. Download the *docker-machine-driver-hyperkit* binary using:
+
----
$ sudo curl -L  https://github.com/machine-drivers/docker-machine-driver-hyperkit/releases/download/v1.0.0/docker-machine-driver-hyperkit -o /usr/local/bin/docker-machine-driver-hyperkit
----

. Enable root access for the *docker-machine-driver-hyperkit* binary and add it to the default *wheel* group:
+
----
$ sudo chown root:wheel /usr/local/bin/docker-machine-driver-hyperkit
----

. Set owner User ID (SUID) for the binary as follows:
+
----
$ sudo chmod u+s,+x /usr/local/bin/docker-machine-driver-hyperkit
----

[NOTE]
====
The downloaded *docker-machine-driver-hyperkit* binary is compiled against a specific version of macOS.
It is possible that the driver will fail to work after a macOS version upgrade.
In this case you can try to compile the driver from source:

----
$ go get -u -d github.com/machine-drivers/docker-machine-driver-hyperkit
$ cd $GOPATH/src/github.com/machine-drivers/docker-machine-driver-hyperkit

# Install docker-machine-driver-hyperkit binary into /usr/local/bin
$ make build
----

For more information, see the link:https://github.com/machine-drivers/docker-machine-driver-hyperkit/blob/master/README.md[hyperkit driver] documentation on GitHub.
====

==== Next Steps

{next-steps}

On macOS, you may also xref:../getting-started/installing.adoc#installing-with-homebrew[install {project} via Homebrew].

[[for-windows]]
== Windows

[[setting-up-hyper-v-driver]]
=== Setting Up the Hyper-V Driver
To use {project} with Hyper-V:

. Install link:https://docs.microsoft.com/en-us/virtualization/hyper-v-on-windows/quick-start/enable-hyper-v[Hyper-V].

. Add the user to the local Hyper-V Administrators group.
+
[NOTE]
====
This is required to allow the user to create and delete virtual machines with the Hyper-V Management API.
For more information, see xref:../troubleshooting/troubleshooting-driver-plugins.adoc#insufficient-privileges[Hyper-V commands must be run as an Administrator].
====

. Add an link:https://docs.microsoft.com/en-us/virtualization/hyper-v-on-windows/quick-start/connect-to-network[External Virtual Switch].

. Verify that you pair the virtual switch with a network card (wired or wireless) that is connected to the network.

. Use the configuration option `hyperv-virtual-switch` or startup flag `--hyperv-virtual-switch` to set the name of the external virtual switch you want to use for {project}.
+
For example, on PowerShell use
+
----
PS> minishift config set hyperv-virtual-switch "External (Wireless)"
----
or
+
----
PS> minishift start --hyperv-virtual-switch "External (Wireless)"
----
+
[NOTE]
====
- The name of the virtual switch is case sensitive.
- The use of the environment variable `HYPERV_VIRTUAL_SWITCH` has been deprecated. Instead `MINISHIFT_HYPERV_VIRTUAL_SWITCH` can be used as a configuration option, although this is not recommended as environment variables on Windows do not support non-ASCII characters.
====

==== Next Steps

{next-steps}

[[setting-up-virtualbox-driver]]
== Setting Up {project} to Use VirtualBox

VirtualBox must be manually installed in order to use the embedded VirtualBox drivers.
VirtualBox version 5.1.12 or later is required.
Ensure that you link:https://www.virtualbox.org/wiki/Downloads[download and install VirtualBox] before using the embedded drivers.

VirtualBox must be identified to {project} through either the `--vm-driver virtualbox` flag or persistant configuration options.

[[use-virtualbox-temporarily]]
=== Use VirtualBox Temporarily

The `--vm-driver virtualbox` flag will need to be given on the command line each time the `minishift start` command is run.
For example:

----
$ minishift start --vm-driver virtualbox
----

[[use-virtualbox-permanently]]
=== Use VirtualBox Permanently

Setting the `vm-driver` option as a persistent configuration option allows you to run `minishift start` without explicitly passing the `--vm-driver virtualbox` flag each time.
You may set the `vm-driver` persistent configuration option as follows:

----
$ minishift config set vm-driver virtualbox
----

[NOTE]
====
The `vm-driver` persistent configuration option must be supplied before `minishift start` has been run.
If you have already run `minishift start`, ensure that you run `minishift delete`, set the configuration with `minishift config set vm-driver virtualbox`, then run `minishift start` in order to make use of the VirtualBox driver.
====

=== Next Steps

{next-steps}

